### ISSUE TITLE
Switch to react-hot-loader v3

### ISSUE THREAD

**Issue by justingreenberg** [react-boilerplate/react-boilerplate#1068]
fall cleaning... maybe we should remove `babel-preset-hmre` as it relies heavily on the now deprecated https://github.com/gaearon/react-transform-hmr the question is: how important is maintaining local (react) component state between HMR reloads?

options:
- try to implement React Hot Loader 3 (but... https://github.com/gaearon/react-hot-boilerplate/issues/97#issuecomment-249862775)
- use vanilla webpack HMR (will lose local component state between HMR reloads)

edit: also see https://github.com/danmartinez101/babel-preset-react-hmre/issues/46

**Comment by mxstbr** [comment]
We should switch to React Hot Loader v3 as soon as it's stable, but I don't see why we shouldn't stick with our current setup for now as it currently works perfectly fine?

**Comment by MoOx** [comment]
If I am correct, without RHL v3 you don't have hot loading for functional components.

**Comment by mxstbr** [comment]
That's true. Does RHL v3 at this state already have support for functional components?

**Comment by MoOx** [comment]
Yeah, I am using it for a few months and it's perfect for me. Also included in Phenomic for a while and nobody reported any issue about it :)

**Comment by mxstbr** [comment]
Alright, let's switch to RHL v3 then!

**Comment by kachkaev** [comment]
Hi guys,

I came up with a question and decided to ask it here since it's related to how the app is being reloaded. When editing certain parts of the app like redux actions, we all constantly see the following message in the browser's console: `[HMR] The following modules couldn't be hot updated: (Full reload needed)`. This is normally followed with a manual page refresh.

I once tried `create-react-app` and got used to their robust _cold_ reloading every time a JS file changes. So after going back to this boilerplate, I started to feel lazy going back to the browser from time to time after seeing a long yellow message in the corner of the dev tools.

I'm wondering how hard would it be to optionally enable _cold_ reloading when `HMR` has failed. I know that this would imply the loss of states, but this is not a problem if redux store is persisted.

Could anyone suggest how to trigger a full reload? Just spent > 1hr on this and gave up :-)

**Comment by manelpb** [comment]
@kachkaev try to create your components using React.Component instead. It will auto reload

**Comment by kachkaev** [comment]
@manelpb yeah I know that I can use `React.Component` instead of `React.PureComponent` or functions, but that potentially creates performance problems. Even if I do so, there will be still cases when webpack won't be able to reload itself and show me that yellow _please refresh_ message in the console. I'm just wondering how I can automate this refresh.

**Comment by jptissot** [comment]
I don't have a complete example of this at hand (only private project code) but I was able to use Webpack 2.2 and RHL3 with this boilerplate. It required some moving of code a bit but It works great !

**Comment by MichaelIT** [comment]
![image](https://cloud.githubusercontent.com/assets/5445733/26025663/2b9fdbfa-381f-11e7-8aed-746bc72e2e5c.png)
I am trying use RHL3 in `dev` branch, But I get some error like @kachkaev . I have spend about 4 hour to google and  fix it.But I am faild.Every time I change component the ,it will reload page. 😢

**Comment by kai23** [comment]
Same as @MichaelIT here, can't make it working.

**Comment by kachkaev** [comment]
Here is what helped in old webpack https://github.com/react-boilerplate/react-boilerplate/pull/1357

Maybe there is an alternative in v2?

**Comment by kai23** [comment]
I'm back to the old hmre for the moment, it doesn't work on everything but it's sill better than nothing. I'm waiting for the 3.5 to see if something changes.

**Comment by kai23** [comment]
I'm back to the old hmre for the moment, it doesn't work on everything but it's sill better than nothing. I'm waiting for the 3.5 to see if something changes.

**Comment by Dattaya** [comment]
Fixed in https://github.com/react-boilerplate/react-boilerplate/pull/1871
