### ISSUE TITLE
npm run clean removes favicon import

### ISSUE THREAD

**Issue by robbieyng** [react-boilerplate/react-boilerplate#1387]
Why is `import 'file?name=[name].[ext]!./favicon.ico';` removed from app.js when the example app is removed? I had a bit of trouble and it took some time to track down this as my problem for why a custom favicon wasn't being added. I added this back in and my newly added favicon worked like a charm.

**Comment by zsherman** [comment]
My solution was to add 'ico' to the allowed file types in the allowed `file-loader` types.

**Comment by robbieyng** [comment]
@zsherman interesting...I am curious what is considered best practice and if we should add to the documentation.

**Comment by mxstbr** [comment]
Seems like a bug, PR welcome!

**Comment by samit4me** [comment]
Thanks for submitting the issue and posting a solution @robbieyng. It certainly looks like this was a bug, but it appears that it was fixed in [this commit](https://github.com/react-boilerplate/react-boilerplate/commit/a09fb22ff591a71d67ee4bb7a45f2f9aee09deee#diff-f0effff2abac7b31e1d10799616d11cb) which was released as part of [3.4.0](https://github.com/react-boilerplate/react-boilerplate/releases/tag/v3.4.0) 18 days after this issue was logged.

I just tested this and it now appears to work, so I hope you don't mind, but I am going to close this issue.
