### ISSUE TITLE
New eslint-plugin-react expects default props

### ISSUE THREAD

**Issue by gihrig** [react-boilerplate/react-boilerplate#1504]
I'm not convinced this is good idea, but see the linked content below for more info. Open to discussion.

Error: ~/react-boilerplate/app/components/Button/index.js 40:3
error propType "handleRoute" is not required, but has no corresponding
defaultProp declaration react/require-default-props (and 34 more)

Disable "react/require-default-props" in package.json
See: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-default-props.md

To reproduce:
Confirm #1501 has merged
Checkout latest `dev` branch
Remove "react/require-default-props" from package.json
`npm test`

Boilerplate 3.4+ `dev` branch (ad871d7a1b70cec5b365fdc30eb86ee7e189158f)
Node 7.4.0
npm 4.1.1
yarn 0.19.1
Mac OS 10.11.6
Chrome 55.0.2883.95 (64-bit))

**Comment by KarandikarMihir** [comment]
IMHO, it looks like a very conservative rule. I find myself in a dilemma.

> ## When Not To Use It
> If you don't care about using defaultsProps for your component's props that are not required, you can disable this rule.

_and_

The compelling [example](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-default-props.md#enforce-a-defaultprops-definition-for-every-prop-that-is-not-a-required-prop-require-default-props). I empathize with the both!

In terms of DX, writing default props for every little prop will be annoying. And the ones who want to impose strict rules can easily enable this. RBP is all about performance and coding standards but this one looks like [Dolores Umbridge](http://www.themarysue.com/wp-content/uploads/2014/10/umbrdieg.gif).  I'd say we should disable this rule globally. But I'll be happy to be convinced otherwise!

**Comment by gihrig** [comment]
In case it's not clear in this context,

> Disable "react/require-default-props" in package.json

Is the way it will be as of #1501 merging.

I'm OK to leave it that way. Other opinions?

**Comment by gihrig** [comment]
>  @KarandikarMihir - I'd say we should disable this rule globally.

>  @gihrig - I'm OK to leave it that way. 

Other opinions?

**Comment by gihrig** [comment]
Been 4 days and no other comments/opinions. The rule is disabled - closing
