### ISSUE TITLE
App manifest icons appear to be broken

### ISSUE THREAD

**Issue by samit4me** [react-boilerplate/react-boilerplate#1567]
The icon "favicon.png" referenced inside of `manifest.json` doesn't appear to exist, so the manifest icons appear broken:

<img width="482" alt="screen shot 2017-02-07 at 11 19 05 pm" src="https://cloud.githubusercontent.com/assets/3248531/22692741/1348b9d8-ed8c-11e6-86aa-a2619ea5f26f.png">

**Comment by gihrig** [comment]
While #1568 handles the OP, a related issue is `apple-touch-icon.png` in various sizes and also a `precomposed` flavor.

I only bring this up because I see many 404'd requests in my error logs for the various apple icons. My app is not mobile optimized, but they keep coming ;-)

As far as I can tell, the apple icons are not related to `manifest.json` or specifically to PWS's, though the purpose is the same.

Thoughts?

PS. I really like the way you hid the icon files away in `App/images...`

**Comment by samit4me** [comment]
Hi @gihrig, good point 👍, thank you for raising that. While it is a similar issue, I believe it is different like you mentioned, so I have opened a new issue #1584 to get that done. Cheers
