### ISSUE TITLE
some file support partial loading, some not

### ISSUE THREAD

**Issue by fkpwolf** [react-boilerplate/react-boilerplate#1573]
One of my favorite features is "Your saved changes to the CSS and JS are reflected instantaneously without refreshing the page. ". 

So I tried to change "app/containers/HomePage/index.js" and it works as excepted. But for "app/components/Header/index.js", after changed, the browser re-loaded fully, as what happen when I press F5 button.

This make me confused. Are there some rules about this case?

**Comment by denisflorkin** [comment]
Hi @fkpwolf, I assume this is most likely due to the fact that "pure functional component" does not allow for hot reloading, that's why a full reload is automatically trigger when a change of this nature happened.

There's mention of this here [#1544](https://github.com/react-boilerplate/react-boilerplate/issues/1544)

**Comment by fkpwolf** [comment]
HomePage extends React.PureComponent so page will reload. I see. Thanks @denisflorkin
