### ISSUE TITLE
Deploy on Azure

### ISSUE THREAD

**Issue by thiagoalmedeiros** [react-boilerplate/react-boilerplate#1577]
Hi everyone, Has anyone ever had a problem deploying in the azure? I'm doing deploy and the following error is returned:

Invalid start-up command "cross-env NODE_ENV=development node server" in package.json. Please use the format "node <script relative path>".

I already made the change but the error persists.

**Comment by samit4me** [comment]
Hi @thiagoalmedeiros, we deploy to Azure at work, but I wasn't involved with any of the setup as I just started recently, so not sure how much help I can offer, but from my understanding, we use Visual Studio Team System (VSTS) for CI, which is essentially running `npm run build` to generate the **build** directory and this static content is pushed up to the cloud.

What is your setup? What Azure product are you using? What triggers the error? Keen to know as I might be able to try and replicate the issue with a fresh copy of the boilerplate.

**Comment by thiagoalmedeiros** [comment]
Invalid start-up command "cross-env NODE_ENV=development node server" in package.json. Please use the format "node <script relative path>".
 Looking for app.js/server.js under site root.
 Missing server.js/app.js files, web.config is not generated
 The package.json file does not specify node.js engine version constraints.
 The node.js application will run with the default node.js version 6.9.1.
 Selected npm version 3.10.8


The problem is that when running the build command and putting it in the static folder the react router does not work.

**Comment by samit4me** [comment]
It's difficult to say what the issue is, are you able to share more detailed information like boilerplate version? Azure product you are using? Any specific setup details you have done, so we could try and replicate?

**Comment by thiagoalmedeiros** [comment]
Hi samit4me, thanks for trying to help me.
The boilerplate version I am using is the "version": "3.1.0".
In relation to azure I am using an application service "web application" in the "F1 free" plan.
I added some new routes to the example "/ dashboard".

**Comment by samit4me** [comment]
Okay thanks, I am assuming your using:
- This product https://azure.microsoft.com/en-au/services/app-service/web/?
- You selected the Node stack?
- Which deployment method did you use? Cloud, local source etc

**Comment by thiagoalmedeiros** [comment]
Yes, that's right.
The method was local git.

**Comment by samit4me** [comment]
Thanks for confirming. Wow, it feels as if I've gone down the rabbit hole 😳 So at work our front-end is bundled in with a .NET app, so that does not help with this problem at all 😞 

I created an Azure account and setup a web app using the node stack with cloud deployment. You'll be happy to know I got the exact same error `Invalid start-up command "cross-env NODE_ENV=development node server" in package.json. Please use the format "node <script relative path>".`.

It would seem this method expects a Node application that is ready to go via `npm start`. I have literally spent the last 4 hours trying to make to happen with `react-boilerplate` but I could only get it to work by checking in the build directory and using another express server setup.


### Website
http://react-boilerplate.azurewebsites.net/

### Configuration
```
// package.json
"start": "node ./www"
```

```
// www

var express = require('express');
var path = require('path');

var buildDir = path.join(__dirname, 'build');

var server = express();
server.use('/build', express.static(buildDir));

// All files
server.get(/\..+$/, function (req, res) {
  let filename = req.path;
  res.sendFile(buildDir + filename);
});

// Everything else
server.get('*', function (req, res) {
  res.sendFile(buildDir + '/index.html');
});

var port = process.env.PORT || '3000';
server.listen(port, function () {
  console.log('server listening on port ' + port);
});
```
https://github.com/samit4me/react-boilerplate/tree/azure

### Moving forward
So, I'm not sure what else to do at the moment, but if you are using local git setup, maybe you could push the build directory along with an express server up to Azure.

If anyone else more experienced with Node / Azure could help with this, that would be fantastic.

**Comment by nicholaslie90** [comment]
I'm also starting out with this project, and had trouble deploying this app to Azure App Service as well. The setup: Azure App Service with Deployment Options set to a Bitbucket repo. All I got was a empty page with the message: You not have permission to view this directory or page.

Strangely I can run the server using npm start on the Kudu console though. But when trying to open <myapp>.azurewebsites.net:3000 nothing happened as well. 

<img width="1440" alt="screen shot 2017-03-14 at 23 55 16" src="https://cloud.githubusercontent.com/assets/4620070/23912326/e3c61b78-0911-11e7-85c1-f585de851ba2.png">

**Comment by thiagoalmedeiros** [comment]
I solved the problem using the solution for angularjs

http://stackoverflow.com/questions/12614072/how-do-i-configure-iis-for-url-rewriting-an-angularjs-application-in-html5-mode

**Comment by elimcjah** [comment]
@thiagoalmedeiros What changes from default did you make to launch to azure?

**Comment by thiagoalmedeiros** [comment]
Basically I needed to change the web.config for the react router to work.

**Comment by timbrand** [comment]
I'm now using the following configuration, which also adds support for the manifest.json-file loading. My azure web app was by default not configured to handle json files.
```
<?xml version="1.0"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="React Routes" stopProcessing="true">
                    <match url=".*" />
                    <conditions logicalGrouping="MatchAll">
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                        <add input="{REQUEST_URI}" pattern="^/(api)" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="/" />
                </rule>
            </rules>
        </rewrite>
        <staticContent>
            <mimeMap fileExtension=".json" mimeType="application/json" />
        </staticContent>
    </system.webServer>
</configuration>
```

**Comment by fmocorreia** [comment]
I was trying to deploy to azure, and even following these directions, I was unable to make the boilerplate working as is in azure. 

Right now I have the error "You do not have permission to view this directory or page." even adding manually the web.config (because it was not autogenerated because of there was no server.js or app.js).

What did you do differently to make this work?

My steps:

- Cloning the react boilerplate
- added the web.config to the root of the project
- Pushing it to my Azure Git Repository (I've configured local repository as deployment option)

**Comment by DVassilev** [comment]
I have been having issues on deploying this for azure too. Could add someone who has managed to get it working from git deployment please update the deployment docs with their steps? @timbrand @thiagoalmedeiros

**Comment by sudopaeg** [comment]
Hi guys, I'm no expert in javascript environment but as I had been struggling to deploy react-boilerplate app to Azure Webapp Service, I thought it would be worth sharing here.

There are few things I had to tweak since I could not find a workaround (kept getting `HTTP 500 internal server error`)
- Make sure the root directory is `site/wwwroot`
- take `server/index.js` file out to root folder and modify the start script to `"start": "node index.js"`
- make sure you set the NODE_ENV variable in App Service Settings to 'production'
- Azure Web App Service runs node on `iisnode`, which requires `web.config` file. The reason why I took the index.js file was because issnode will look for the `entry js file` and `package.json` file in the same folder for some reason. 
- Below is the web.config file I used. Placed `web.config`, `package.json`, and `index.js`in the root directory. 
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <system.webServer>
        <webSocket enabled="false" />
        <handlers>
            <add name="iisnode" path="index.js" verb="*" modules="iisnode"/>
        </handlers>
        <rewrite>
          <rules>
            <!-- Do not interfere with requests for node-inspector debugging -->
            <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
              <match url="^index.js\/debug[\/]?" />
            </rule>
    
            <!-- First we consider whether the incoming URL matches a physical file in the /public folder -->
            <rule name="StaticContent">
              <action type="Rewrite" url="public{REQUEST_URI}"/>
            </rule>
    
            <!-- All other URLs are mapped to the node.js site entry point -->
            <rule name="DynamicContent">
              <conditions>
                <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
              </conditions>
              <action type="Rewrite" url="index.js"/>
            </rule>
          </rules>
        </rewrite>
        <httpErrors existingResponse="PassThrough" />
    </system.webServer>
</configuration>
```

React Router and API calls are all working correctly for me.
