### ISSUE TITLE
How: form onSubmit jump to '/route/valueOfInputField' child:route?

### ISSUE THREAD

**Issue by rentrop** [react-boilerplate/react-boilerplate#1582]
Following the excelent exmaple app:
How can i `onSubmit` go e.g. a child route per user so: `/user/:username`?
I found how to setup [dynamic-routes](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/js/routing.md#dynamic-routes) and also that using [`push`](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/js/routing.md#usage) is the right way to go there.

I tried:

```
import { push } from 'react-router-redux';

export function mapDispatchToProps(dispatch) {
  return {
    onChangeUsername: (evt) => dispatch(changeUsername(evt.target.value)),
    onSubmitForm: (evt) => {
      if (evt !== undefined && evt.preventDefault) evt.preventDefault();
      dispatch(push('/user/' + evt.target.value);
    },
  };
}
```

`evt.target.value` is undefined. If this is the way to do this: How can i get the value of the `#username` input field?

Also using `dispatch(push('/user/' + makeSelectUsername());` did not work... 
Do i need to setup a saga that takes the username from `makeSelectUsername()` as it is done [here](https://github.com/react-boilerplate/react-boilerplate/blob/master/app/containers/HomePage/sagas.js#L18
)?

**Comment by samit4me** [comment]
Hi @rentrop, I believe `evt.target.value` is `undefined` because only form element have a value. Given that you are storing the form values in the Redux store, well I can only assume `onChangeUsername: (evt) => dispatch(changeUsername(evt.target.value))` that places the username into the store??? Well assuming it does, can you pull username out of the store for use in the `onSubmitForm` method???

Another possible solution to using Redux, might be to use Refs, see [Refs and the DOM](https://facebook.github.io/react/docs/refs-and-the-dom.html).

I hope that helps, or at least gives your some options, please let me know how you go with it!

**Comment by rentrop** [comment]
Thanks @samit4me. 
Could you please tell me how to pull it out of the store in `onSubmitForm`?

I am not sure how to access it within the `mapDispatchToProps`... 
I tried using `ownProps` (in `mapDispatchToProps`) which doesn't seem to work. I am not sure how to access the state in `mapDispatchToProps`...

So far i access the store using 

```
const mapStateToProps = createStructuredSelector({
  username: makeSelectUsername(),
});
```

Then i can reference the username using `this.props.username`. Obviously `this` is not meaningful inside `mapDispatchToProps`... 

Very much appreciate your help
