### ISSUE TITLE
HRM support (Hot reload) for sagas

### ISSUE THREAD

**Issue by daveamit** [react-boilerplate/react-boilerplate#1583]
Hi,
  First of all let me express my gratitute, you guys are awesome! **react-boilerplate** was a tremendous help to really kickstart a new project.
   That said, I recently implemented hot-reload for Sagas, Should I submit a PR? Please let me know if this feature is in roadmap.

Thanks.

Again, I love what you guys are doing! Keep up the good work!

**Comment by KarandikarMihir** [comment]
Hi @daveamit That is really great! Regardless of what's in the roadmap, you can always share your ideas :) We'd love to see your work to enable hot reloading sagas. Can you provide more code or create a repo demonstrating your feature? So that others can jump in and we can have a discussion. Cheers!

**Comment by daveamit** [comment]
Hi @KarandikarMihir,
   Sure thing! I'll fork this one, implement the feature and share the repo link here.

**Comment by Dattaya** [comment]
Sagas injected via `injectSaga` are now hot reloadable, see https://github.com/react-boilerplate/react-boilerplate/pull/1871
