### ISSUE TITLE
Pointers on config for web and electron app?

### ISSUE THREAD

**Issue by tauren** [react-boilerplate/react-boilerplate#1586]
I'm looking for pointers on getting my application configuration set up to support both a webapp (which this boilerplate already does) as well as an Electron app. 

I've started off with some basic changes:

* add `"main": "electron/main.js"` to `package.json`
* create `/electron/main.js` file 
* point at `/build/index.html` from the `main.js` file
* add a script command `npm run electron`

However, I'm unclear on several things:

* should I add variants of the webpack configs for dev vs prod and webapp vs electron environments?
* what changes would need to be in a `webpack.electron.babel.js` file?
* should I add variants of the npm scripts for dev vs prod and webapp vs electron environments?
* how to get this working in dev vs prod mode since web assets are in-memory in dev mode?

Has anyone done this? I'd love to get some pointers.

Is Electron support something that would be worth adding to this boilerplate?

**Comment by gihrig** [comment]
@tauren Because Electron is basically a combined client/server runtime, I would think that you would have to install the entre boilerplate in Electron to run in dev mode. That's probably not what you want to ship as a final product?

> Has anyone done this? I'd love to get some pointers.

I've never done it, but I would think you would need to, more or less, complete your app and install the production build in Electron, and tweak that to get things working smoothly.

If you haven't already, try searching this repo for `is:issue electron`. There have been a few discussions on this.

> Is Electron support something that would be worth adding to this boilerplate?

That depends on what you mean by 'Electron support'. Modifying the boilerplate so it's a better fit for Electron: probably not. This seems more like a specialized deployment issue than a core boilerplate issue.

On the other hand, there is a [deployment](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/deployment.md) page in the docs. If packaging a boilerplate app in Electron is of similar complexity to the deployments listed there, an electron section would be welcome. If it's more complex, a separate docs page would still be welcome.

I have a use case for RBP in Electron coming up in a few weeks, so I am interested to hear how this goes. Please keep us informed.

**Comment by Necmttn** [comment]
@tauren I haven't done it before. but currently i'm working on electron project.(so i could say i have a little experience) as experimental I will try to create react-boilerplate-electron version. 

i'm not expert in the area so all the help is welcome. 

when i finish initial setup i will pass link to here. 
Cheers.

**Comment by blling** [comment]
Please search or ask on StackOverflow.
