### ISSUE TITLE
PropType not defined for updateProgress in ProgressBar

### ISSUE THREAD

**Issue by nidsnitesh** [react-boilerplate/react-boilerplate#1607]
Hi

Please check [this](https://github.com/react-boilerplate/react-boilerplate/blob/master/app/components/ProgressBar/ProgressBar.js#L94) line

`PropType` is missing for `updateProgress` in `ProgressBar` component.

Is it intentionally done ?

**Comment by KarandikarMihir** [comment]
@nidsnitesh Hi! Yeah, it was intentional. Because `ProgressBar` does not access `updateProgress` as `this.props.updateProgress()`, but instead it passes all of the props to `handleProps()`. If you add it as a `propType`, ESLint would throw following error: 

```javascript
'updateProgress' PropType is defined but prop is never used
```

I'm not sure if it is a bug on ESLint's part. But you're right. `updateProgress` is never accounted for in `propTypes`. Do you think you can get to the bottom of this?

**Comment by blling** [comment]
`ProgressBar` has been removed from the latest version :)
