### ISSUE TITLE
Hot reload not working

### ISSUE THREAD

**Issue by theterra** [react-boilerplate/react-boilerplate#1641]
Dev mode:
Changing code in js files, css files(styled components) doesn't do anything on the browser.
Mostly one or two times changes happening on the browser. After that remains same or shows  previous commits. Changes doesn't come to normal until I rebuild.
I'm having a hard time figuring out how to fix this

Ps: Not using functional components

**Comment by gihrig** [comment]
@prudhvisays 
>Ps: Not using functional components

Are you using `PureComponent`s? That does not work with the current HMR set up either.

**Comment by prudhvisays** [comment]
@gihrig am not using pure components

**Comment by prudhvisays** [comment]
my app.js file
```
export default class App extends React.Component {

  static propTypes = {
    children: React.PropTypes.node,
  };

  render() {
    return (
      <Layout className="ant-layout-has-sider">
        {!!localStorage.token && <SideBar/> }
        <Layout>
          <HeadBar/>
          <Content style={{ margin: '1em 1em', padding: 20, background: '#fff', minHeight: '85vh' }}>{React.Children.toArray(this.props.children)}</Content>
      </Layout>
    </Layout>
    );
  }
```

**Comment by juanda99** [comment]
Not enough watchers? Take a look here https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md

**Comment by YouriT** [comment]
I don't know about you but if you do something as simple as:
`git clone git@github.com:react-boilerplate/react-boilerplate.git`
`npm run setup`
`PORT=3001 npm run start`
Edit: `app/components/A/index.js` by just changing the color of the link => I don't have any hot reloading neither.

**Comment by lpillonel** [comment]
It is also not working for me : (

**Comment by YouriT** [comment]
So indeed, it doesn't work out of the box. A simple way to get it working, is to change your containers that are extending `React.PureComponent` by `React.Component` and it will work like a charm. Or at least it worked for me.

What I just found a bit sad is that it doesn't work "out of the box" and so it's misleading as the boilerplate is using PureComponents...

**Comment by lpillonel** [comment]
Too bad hot reload works only with Components class.

I see a [boiler-plate](https://github.com/wkwiatek/react-hot-loader-minimal-boilerplate) working with Components / PureComponents / pure function components

Can we have something similar ?

**Comment by jwyuen** [comment]
I'm also having this issue although I'm not sure if it's the same problem since it doesn't I'm not using `PureComponent` but just `React.Component`.  I upgraded to rbp 3.4 but I'm still using PostCSS  and css files and I'm having inconsistent HMR behavior when a css file gets edited.  Editing a css file will always trigger a rebuild, but it won't always correctly reload the css file which when it does shows this message from `process-update.js`:

`[HMR]  - ./~/css-loader?localIdentName=[local]__[path][name]__[hash:base64:5]&modules&importLoaders=1&sourceMap!./~/postcss-loader!./app/components/ContractsCard/styles.css`

**Comment by jwyuen** [comment]
Ok I updated my webpack version from 2.2.0-rc.3 to the latest 2.3.1 and I haven't observed any problems yet so it might've just been an issue with webpack.......

**Comment by prudhvisays** [comment]
I went through the @juanda99  answer 
_**Here is the solution**_ 
**Step: 1**
update webpack version from  2.2.0-rc.3 to the latest 2.3.1
in webpack.dev change new webpack.NoErrorsPlugin() **to** new webpack.NoEmitOnErrorsPlugin()
**Step: 2**
Working with editors/IDEs supporting “safe write”
Note that many editors support “safe write” feature and have it enabled by default, which makes dev server unable to watch files correctly. “Safe write” means changes are not written directly to original file but to temporary one instead, which is renamed and replaces original file when save operation is completed successfully. This behaviour causes file watcher to lose the track because the original file is removed. In order to prevent this issue, you have to disable “safe write” feature in your editor.

IntelliJ - Settings ▶︎ System Settings ▶︎ Synchronization ▶︎ disable safe write (may differ in various IntelliJ IDEs, but you can still use the search feature)
 
**Reference**
https://webpack.github.io/docs/webpack-dev-server.html#working-with-editors-ides-supporting-safe-write

**Comment by KarandikarMihir** [comment]
@prudhvisays Thanks for posting the solution here. @lpillonel Does that work for you?

**Comment by lpillonel** [comment]
Well, It was working at my home last last week, but still have an issue at work. Will check again

**Comment by KarandikarMihir** [comment]
@lpillonel Let me know, thanks a lot!

**Comment by emzero** [comment]
Any updates on this?

I've updated to latest webpack (2.4.1) but still getting a full page refresh when changing JS/CSS code.

This goes against the supposed feature of "Instant Feedback" that shows everywhere.

Is this project being maintained?

**Comment by kai23** [comment]
@emzero you can still change all `extends React.Component` to `extends React.PureComponent`

**Comment by westhomas** [comment]
FWIW, http://www.frontendjunkie.com/2017/04/react-stateless-components-used-for.html

As long as the first level components are impure, everything works great.

**Comment by rkmax** [comment]
I'm having this issue today, I have updated to the latest webpack and also tested with 2.3.1 without look :(

**Comment by rkmax** [comment]
today, I have cloned and do check out v3.4.0 then run setup, clean do some change and hot reload is not working, :disappointed:

**Comment by kai23** [comment]
@rkmax event if you  `extends Component` instead of `extends PureComponent` ?

**Comment by rkmax** [comment]
@kai23 yes, the page always get refreshed

**Comment by Dattaya** [comment]
Hot reloading was fixed in `dev`: https://github.com/react-boilerplate/react-boilerplate/pull/1871. It now works for any components, reducers, injected sagas and translation files.
