### ISSUE TITLE
can we use browserify instead of webpack for building? Please Its important for me this question.

### ISSUE THREAD

**Issue by filipveschool** [react-boilerplate/react-boilerplate#1684]
Hi, I know this sounds maybe weird, but I am wondering if it would also be possible to compile the project and offline parts with browserify building?

I am doing my internship right now and the company that I am working want me to use browserify instead of webpack because they know how to use browserify and are not familiar with webpack.

I know this sounds stupid, but would it be possible, or do I have to tell them that its not possible to use browserify?

I only have a month left for my internship for graduation and now they suddenly said that I have to use browserify instead of webpack that I could choose at first. Not very professional, but I hoped you would/could help me maybe by helping thinking about it if it would be possible then to use browserify?

**Comment by theseushu** [comment]
No, its not possible.

Especially the offline parts. It's done by 'webpack-offline-plugin'.

It is possible to set up a similar framework using browserify or whatever you want without webpack, but not possible for an intern in one month

My suggestion 1: try something else. You can try this site: http://yeoman.io/
suggestion 2: Ask your mentor instead of online. You don't have a mentor? They want an intern without any guidance to be responsible of this? Just give them anything, they don't really care.
