### ISSUE TITLE
Feature request as part of npm run setup

### ISSUE THREAD

**Issue by Aftabnack** [react-boilerplate/react-boilerplate#1719]
## What's happening now

* It is blindly clearing my .git folder which removed the repository that I already cloned

## Proposal

* If we are sure people are cloning from here, we can do the following
    * Check if `.git` folder exists
    * If yes, check `.git/config` to check the remote URL to be this URL
    * Only if both the checks pass, clear the .git folder and re-init

**Comment by gihrig** [comment]
@Aftabnack You're on the right track. This was started under #760. I just haven't had time to work on it.

If you're inclined to work on #760 go ahead.

**Comment by Aftabnack** [comment]
@gihrig I will work on this and give a PR

**Comment by gihrig** [comment]
> I will work on this and give a PR.

Great news ✨ 

Please continue the discussion on #760.

**Comment by Aftabnack** [comment]
I have finished implementing this. For committing, it's looking for commit message template. Is it mentioned in the docs here?

**Comment by gihrig** [comment]
See [CONTRIBUTING.md](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#pull-requests).

Some how this got hidden away in `.github`. Another welcome PR would be simply moving it back to the project root where people can actually see it.

**Comment by ckeeney** [comment]
I was just bit by this.  I didn't clone from this repo, because I already have a git repo I initialized with a README.  I intended on trying out different boiler plates in separate branches, and merging in my final decision into master.

The installation instructions say to clone from the repo, but this isn't possible if you already have a repo.  I downloaded the latest release from the releases page and extracted it into my repo.  I then ran `yarn setup`.  I'm not entirely sure what it did, except that it left my repo in some kind of bad state.  At a minimum it removed the origin remote.

**Comment by Aftabnack** [comment]
It does `git init` at the end of the setup. I've finished a PR on this. You will now be able to retain your git repo. 



Only if the project is cloned from this repo and doesn't have any other remote, it will ask you now if you want to remove the git history.

**Comment by gihrig** [comment]
Closed by #1720.
