### ISSUE TITLE
Prepare for v3.5 release

### ISSUE THREAD

**Issue by justingreenberg** [react-boilerplate/react-boilerplate#1776]
i [created a milestone](https://github.com/react-boilerplate/react-boilerplate/milestone/4) to aggregate outstanding PRs we want to include in next release... i think we're a little overdue :) please let me know what you guys think

cc @react-boilerplate/core

edit: raw link - https://github.com/react-boilerplate/react-boilerplate/milestone/4

**Comment by vicbell** [comment]
I think #1746 should be include:)

**Comment by Aftabnack** [comment]
I think #1720 should also be part of it.

**Comment by mydearxym** [comment]
server side render(#1236) wanted !

**Comment by justingreenberg** [comment]
@Aftabnack #1720 is included

@vicbell @mydearxym unfortunately #1746 and #1236 are incompatible with one another

a great deal of effort has been put into both of these PRs, as maintainers we owe it to these contributors to make a decision sooner than later

### Bifurcation Rant...

the simple fact is— the "js ecosystem" is evolving faster and faster... [`create-react-app`](https://github.com/facebookincubator/create-react-app) is more than enough for 80-90% of frontend (browser only) use cases, the team is world-class, shipping non-stop, and their dependency-based model makes maintenence almost too easy.

at the same time, [`next.js`](https://github.com/zeit/next.js/) is totally changing the game for SSR apps, has incredible DX, and again there are very smart people working on improving complex issues as you're reading this. even as one of the architects of `react-boilerplate`, i have personally used both CRA and next.js for projects in the past few months and have been blown away by the productivity.

that said, **we probably need to reflect a little bit on where RBP fits in this brave new world** and how we want to position ourselves. for posterity, i'm inclined to upgrade react router with an explicit understanding going forward: this project is for creating _**large, high-performance enterprise-grade frontend applications with advanced/custom requirements, statically delivered by CDN**_.

would love to hear thoughts from community, maintainers and the godfather (@mxstbr 🙇)

my opinion is just based on recent experience... i'm currently using RBP for a complex application with security and compliance requirements that would be compounded by the increased attack surface introduced by server rendering... so, as an advanced user i chose RBP based on these requirements and knowing the value of stable i18n, redux-saga, code-splitting, etc.

`<end-of-rant/>`

what do you think?? please leave your comments below! 

if you just want to "vote" for one or the other, please thumbs up 👍 comment above...
 - [react router v4 suggested by vicbell](https://github.com/react-boilerplate/react-boilerplate/issues/1776#issuecomment-304146062)
 - [SSR support suggested by mydearxym](https://github.com/react-boilerplate/react-boilerplate/issues/1776#issuecomment-304169957)

feedback from the community will help drive our decision and is much appreciated! 🙏 feel free to evangelize one way or the other, but no "+1" comments por favor ;)

---

open PRs not [currently included](https://github.com/react-boilerplate/react-boilerplate/milestone/4) but worth considering (imho):
 - #753 - Dockerize (very old, shouldn't be too hard to wrap up tho)
 - #1207 - RHL v3 (hmre preset has been deprecated forever)

**Comment by anuraaga** [comment]
Thanks for starting this discussion - I agree with @justingreenberg's mission statement (large, high performance...CDN) completely. Personally, the biggest reason for using RBP for me among the many boilerplates that exist is that most boilerplates are designed for use with nodejs and isomorphic rendering - RBP has many great features and encourages best practices for a purely static site, which is perfect for me who uses a static site that hits a Java API server; I have no plans on moving API development to nodejs for a variety of reasons. I hadn't looked at `create-react-app` recently and it looks like it has a lot of good features now, but not enough for production apps I think, and after adding such features in, we'd be back at RBP.

Also, FWIW, I had mostly done server-side development in the past, with just a bit of raw React before Flux was a think, but thanks to having RBP to mimic best practices from, I was able to jump into high quality, production-level web client development very easily and learned a lot about the JS ecosystem. I imagine if I had started with `create-react-app`, the result would have been of a lot worse quality. Perhaps I would extend the mission statement to include `, with an eye for encouraging best practices for high quality web development.`

**Comment by Dattaya** [comment]
I would vote for #1746. If my memory serves me right, last @mxstbr's decision regarding SSR was to split #1236 into multiple PR's and bring `react-boilerplate` closer to supporting universal rendering gradually. Last such PR that requires our attention is: #1591. Ideally SSR support would be easily removable not everyone needs it and the complexity it introduces.

**Comment by samit4me** [comment]
You make some great points @justingreenberg, I too have been asking myself where does RBP fit in this brave new world with the likes of [create-react-app](https://github.com/facebookincubator/create-react-app) and [next.js](https://github.com/zeit/next.js).

I haven't contributed much of late due to a lack of free time, but I certainly get the feeling we need to decide on the future direction of this project. I do remember a discussion with Max (can't find it now, [could find this one](https://github.com/react-boilerplate/react-boilerplate/pull/1515#issuecomment-274940698)) discussing the options of creating a [fork of create-react-app](https://github.com/facebookincubator/create-react-app/issues/682) but applying some of the best features from RBP, for example:
-  i18n
- styled-components
- redux state management
- scafolding tools

The above list is what I found to be the most usefull from RBP as it fits my usecase very well, but another developer might want / need Flow or TypeScript or server-side rendering. The point I'm trying to make is that it's impossible to create a silver bullet and I believe the best we can do is decide on a minimal feature set and do it very well.

If it's possible we should try and architect it in a way that allows the project to be extended so requested features that fall outside the "minimal feature set" can be easily added. That feature could then be documented or forked in another repo.

Maybe this is a little out of scope for this issue, but would like to hear what others think. Should we open another issue to come up with a minimal feature set?

As for version 3.5 can we add:
- #1746 Migrate to react router v4
- #1698 Add Debugging section in Docs + VS Code instructions
- #1785 Update README.md

**Comment by Dattaya** [comment]
> I do remember a discussion with Max (can't find it now, could find this one) discussing the options of creating a fork of create-react-app 

I was searching for it but couldn't find that discussion either.
This is what I was thinking to try to do, but my opinion might change once I start experimenting:
- Create CRA fork with 
  - webpack dll, 
  - some other important features but not everything, 
  - a simple way to extend a webpack config instead of ejecting: ```({ config, mode }) => { config.module.loaders.push(...) ...```. I've seen Neutrino and their plugin system (presets), on one hand I like it because I wanted to do something like this myself, on the other I can't decide if it's over-engineering or not.
- Extract useful components like `ProgressBar` into a separate repository in this organization and publish on npm
- Extract generators into a separate package or add them to a CRA fork? Instead of `clean` script create two: 'generate basic app' and generate 'example app'. Example app is what we ship by default now.

Added #1746 to the milestone as it got more votes.

**Comment by mxstbr** [comment]
I'm in the middle of starting a company and building a product, so I haven't been able to do much work on `react-boilerplate` recently. (gotta get that app shipped! :shipit:)

Just wanted to chime in that a) **go forth and release**, don't wait for me and be blocked, and b) I agree with everything @justingreenberg said.

**I love love _love_ @Dattaya's plan above**, it's exactly what I was planning on doing but haven't had the time to. (and won't have for another good few months) `create-react-app` is a superb base to build upon, and if we can showcase some of the great ideas the amazing minds in the React community have come up with based on that minimal base that'd be (imo right now) the best way forward for `react-boilerplate`. Please start experimenting in that direction! (and get that new release out :fire:)

**Comment by mcz** [comment]
I would love to see FlowType in RBP. I think it would highly increase robustness of the applications. Is there any plan for this? I would love to join and help.

**Comment by Jonathan-Steinmann** [comment]
React deprecated PropTypes as of version 15.5.0, let's switch to using prop-types library

Switch to using prop-types library instead of React.PropTypes #1727
https://github.com/react-boilerplate/react-boilerplate/issues/1727

**Comment by Dattaya** [comment]
@Jonathan-Steinmann, it was done in #1787

**Comment by alexcurtis** [comment]
We are looking at using this boilerplate, but are interested in react router 4. When do you guys think this v3.5 will be released?

**Comment by g0ddish** [comment]
I'm also interested in moving this milestone along; if there is anyway I can be of assistance in getting some of the 29 PRs dating back to Dec '16, Jan, Feb etc. rolled up I would love to help out 😃 . I am slightly concerned the last offical release was ~7 months ago. I get you are busy with real life/work too @mxstbr so sorry for the nagging. Thanks.

**Comment by gihrig** [comment]
@alexcurtis 
1. Understand this is a community project. No single member (not even @mxstbr, our godfather) is required for any given release.

2. Please feel free to jump right in and contribute anywhere you feel you are able to make a meaningful contribution. 

It's great to have you on board 😄

**Comment by vicbell** [comment]
@gihrig  @KarandikarMihir  I found the `input` and the `select` is displayed unnormal(The border looks ugly) after upgrade `sanitize.css` to `5.0.0`, maybe you should take a look at this?

**Comment by iamsolankiamit** [comment]
I would suggest that each Pull request which should accompany a migration path, so when we move from 3.4 to 3.5 we can compile them easily into a readme.

It would be easier to add migration plan for each pull request than to add it later. Some pull request can be ignored like bug fixes, etc.  

Do let me know what you guys think. I'd be happy to help in this direction.

**Comment by siarheipashkevich** [comment]
Hello, guys. When do you plan the next release?

**Comment by justingreenberg** [comment]
@react-boilerplate/core i just merged #1746 (RR v4, react-loadable, asyncInjector refactor)... this is the largest core change since we implemented i18n. huge props to @anuraaga and @Dattaya for their hard work on landing this.

this was really the last serious update on roadmap... was there anything we wanted to include?

feedback on changes introduced in #1746 would be much appreciated 🙏

**Comment by KarandikarMihir** [comment]
@justingreenberg I think webpack 3 also needs to be a part of RBP 3.5.. Not sure if everyone's onboard with it..

**Comment by vicbell** [comment]
I think RBP is now lost. Forgive me to say that. ^^

**Comment by KarandikarMihir** [comment]
#1849 is also worth adding! :)

**Comment by vicbell** [comment]
All request has done, it is ready to release 3.5 ?  ^^

**Comment by KarandikarMihir** [comment]
@vicbell Just want to land the last PR then we're good. #1832 :)

**Comment by justingreenberg** [comment]
@KarandikarMihir merged #1832 

@react-boilerplate/core let's ship!!

**Comment by mxstbr** [comment]
YESS, FINALLY! DO IT!!! :tada:

**Comment by Jonathan-Steinmann** [comment]
will 3.5 be a breaking change?  when will this ship?

**Comment by KarandikarMihir** [comment]
@Jonathan-Steinmann Yes. It will be a breaking change. I don't think there will be a migration plan. But we'll chalk up a change log or a list of PRs that were successfully merged.

**Comment by kopax** [comment]
I have tested the 3.5 and it work great thanks everyone!

I have created https://github.com/react-boilerplate/react-boilerplate/pull/1921 , I think it should be considered for 3.5 as a completion of RR4 change.
