### ISSUE TITLE
Add React Storybook

### ISSUE THREAD

**Issue by greg-murray-volusion** [react-boilerplate/react-boilerplate#1847]
## Issue Type

- [ ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [X] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description
A key feature of a boilerplate project should be easily reusable components.  Adding [React Storybook](https://storybook.js.org/) would enable easy discovery of the existing components and containers already under the app folder.

Here is a sample screenshot of a few react-boilerplate components in a storybook:
![storybook example](https://raw.githubusercontent.com/greg-murray-volusion/react-boilerplate/master/docs/storybook/react-boilerplate-storybook-example.png)

Here is a [sample commit from above](https://github.com/greg-murray-volusion/react-boilerplate/commit/6a7a7b0ccb077166f10643d4c1f83db457e5d242) just to get started if this is something you would like to pursue and like help with.

**Comment by ms88privat** [comment]
Very good idea, storybook is quite good to develop good components!

**Comment by Jonathan-Steinmann** [comment]
It's a great idea, provided you want to create your own generic components.  I think most people would be better served to simply leverage an existing library, like material ui, that already done the work for you

**Comment by MouhamedAymen** [comment]
Storybook is like the most necessary library for react components development. It's nice to have it included OOB, or at least making it ready so that a mere storybook npm install is all what is required (no further config needed).
I am aware this boilerplate is not meant for beginners but storybook is very popular and used by the most of react developers. So why not?

**Comment by gihrig** [comment]
In my experience with Storybook, integrating it into boilerplates varies (I have not tried with this one), but some points of interest:

Storybook works as advertised with Create React App, but due to many small conventions, transferring components from one BP to another has minor incompatibilities. These can add up a large PITA if there are many components.

I successfully adapted Storybook to the ReactQL boilerplate. That required considerable effort, mostly due conflicting webpack configuration. At the time I did this, Storybook used Webpack 2 which did not play well with the Webpack 3 boilerplate environment. Storybook has since upgraded to Webpack 3.

Expansion of components to include additional technologies such as redux or graphql conflict with Storybook configuration. I expect many problems in this area with RBP.

As a single developer, I find developing components in the boilerplate of final use to be ultimately more productive than the trade-offs necessary to integrate Storybook into my workflow. If a larger team intends to use Storybook for component sharing, this may be a more important factor.

Still, if someone wants to do the work of integrating Storybook into RBP and open a working PR, that would be the most convincing argument.
