### ISSUE TITLE
Confused between components and containers

### ISSUE THREAD

**Issue by shahafa** [react-boilerplate/react-boilerplate#1856]
I struggle to understand the difference between components and containers.

I read https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0 and for my understanding presentational component purpose is how things look (markup, styles) and container purpose is how things work (data fetching, state updates)

So take for example https://github.com/react-boilerplate/react-boilerplate/blob/master/app/containers/FeaturePage/List.js which is a pure presentational component which can be reuse between components, why is it placed inside the containers folder?

```
import styled from 'styled-components';

const List = styled.ul
  font-family: Georgia, Times, 'Times New Roman', serif;
  padding-left: 1.75em;
;

export default List;
```

**Comment by jeremyadavis** [comment]
You're correct that that component isn't a container. It's there because it relates to the FeaturePage index.js, which incidentally itself isn't a container because it's just a static page. Personally I keep small styled components like this in the parent file or I create a 'subcomps' folder and place them there.

Most application pages in real world applications would have some kind of data fetch involved so the creators of this boilerplate had to choose between putting the features page in it's correct location ,which is Components, or keeping the page along with the other pages which are containers.

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate. If you're looking for help, check out [StackOverflow](https://stackoverflow.com) and post your question there.
