### ISSUE TITLE
Component Organization

### ISSUE THREAD

**Issue by tanichols** [react-boilerplate/react-boilerplate#1875]
I'm still working through all the potential implications of this, but I'd like to see a bit more organization with regard to the components. The current structure of containing the reducers, styles, etc with the component is ideal, but this still leaves us with a large directory of potentially unrelated components and containers. 

I propose the following:
```
src/
├── screens/
│   ├── screen-a/
│   │   ├── containers/
│   │   ├── components/
│   ├── screen-b/
│   │   ├── containers/
│   │   ├── components/
├── common-components/
│   ├── containers/
│   └── components
├── ...
└── ...
```
With this type of structure, common or shared components can be easily found in the `common-components` directory, while those that are specific to a certain screen can be found in that screen's directory. This might also encourage others to recognize potential containers that are not necessarily a screen, I've often heard containers used synonymously with screen, but there are many other uses for container components. 

I'd love to hear thoughts on this, as well as potential issues with this approach.

**Comment by tanichols** [comment]
I've finally taken the time to read the entire thread on application structure (#27). With all of that context, I wanted to clarify my proposal.

**1.** First and foremost, let's discuss the problem that is the sheer size of the components and containers directories. This is especially true when creating base components such as `<button` or `<h1>`. This is simply unmanageable at scale. I agree with @nareshbhatia when he suggested grouping components by feature, instead of by type. The application structure should allow components to be grouped by page/screen and should include a common/shared directory. The common/shared directory and the pages/screens directories should be further organized by type. I can see three major types. `base-components`, `compound-components`, and `containers`.

**2.** There's this notion that pages/screens are the only containers, and everything else is a component. This is not something we want to propagate in a boilerplate. There are many uses for containers, and not just the pages/screens, though these are easily the most noticeable. Imagine a chat application, with a list of threads in a sidebar, and the current thread open in the main content area. Also imagine a message composer with text, attachments, send, and so on. Each of these areas might be considered a container mapped to different pieces of state.

**3.** Finally, let's consider working on large teams with this approach. Each team may be working on a different page/screen in the application. Without the organization around pages/screens, there is a higher likelihood of one team changing a component that impacts more than just their team. By setting up some 'walls' we have an area with common components like `<header>`, `<footer>` and `<button>` as well as an area for page/screen specific components and containers. 

Having said all that, and having read through the existing discussion, here is my expanded structure tree:

```
app/
├── screens/
.   ├── screen-a/
.   .   ├── containers/
.   .   ├── components/
.   .   └── tests/
.   ├── screen-b/
.   .   ├── containers/
.   .   ├── components/
.   .   └── tests/
├── common/
.   ├── containers/
.   ├── compound-components/
.   ├── base-components/
.   └── tests/
├── ...
└── ...
```

### app/screens/***
Each unique page or screen in the application would have a directory. This directory would contain the containers and components for that screen. It might also be wise to add the screen container and associated a/c/r's in the root of this directory, and use the containers and components directories for the children of the screen

### app/common/base-components
This would contain all the basic building blocks, things like `<button>`, `<h1>`, and `<a>` components. Most of these would map to existing html elements, and would be very basic styled components. No containers here

### app/common/compound-components
This would contain components that are made up of multiple base-components. These would still be stateless, but would be things like `<footer>` or `<gravatar>`

### app/common/containers
These would be shared containers across pages, things like `<sidebar>` or `<nav>`

Again, I'd love to hear thoughts or concerns regarding this this approach.

**Comment by gretzky** [comment]
Fork this and then open a pull request so we can see it in action.

I currently have the following setup in my fork-- with the differences in `app/` folder structure and webpack structure.

```
project/
├── app/
│   ├── index.html
│   ├── assets/
│   │   ├── fonts/
│   │   └── images/
│   └── js/
│       ├── components/
│       │   ├── Button.js
│       │   ├── Header.js
│       │   └── Toggle.js
│       ├── containers/
│       │   ├── Form.js
│       │   └── Nav.js
│       ├── reducers/
│       │   ├── Home/
│       │   │   └── index.js
│       │   └── index.js
│       ├── routes.js
│       ├── screens/
│       │   ├── Contact.js
│       │   └── Home.js
│       ├── store.js
│       ├── styles/
│       │   ├── Controls/
│       │   │   ├── Button.js
│       │   │   └── index.js
│       │   ├── Inputs/
│       │   │   ├── Dropdown.js
│       │   │   ├── Input.js
│       │   │   └── index.js
│       │   └── Type/
│       │       ├── Body.js
│       │       ├── Headers.js
│       │       └── index.js
│       └── app.js
├── build/
├── config/
│   ├── generators/
│   ├── scripts/
│   ├── templates/
│   └── webpack/
│   │   ├── config/
│   │   │   ├── devServer.js
│   │   │   ├── paths.js
│   │   │   ├── plugins.js
│   │   │   ├── resolve.js
│   │   │   └── rules.js
│   │   ├── dll/
│   │   │   ├── package.json
│   │   │   └── vendors.dll.js
│   │   ├── webpack.config.js
│   │   └── webpack.dll.js
│   └── config.js
├── server/
│   └── index.js
├── .babelrc
├── .editorconfig
├── .eslintrc.json
├── .gitignore
├── CHANGELOG.md
├── README.md
└── package.json
```

Generally, I agree with the idea of grouping things together- but too many nesting folders can be a pain, especially with resolving as well as just having too many places to put something. 

As an app scales, personally I think the amount of groups shouldn't be increased; things should be put into existing boxes and truncated. The more folders of things you have, the more apt you are to start repeating or overwriting code because there are just too many boxes to put things in.

**Comment by sorenhoyer** [comment]
I'm sponsering why this issue didn't receive much attention. We could certainly use a good discussion about this. Especially since the styled objects are just floating almost randomly around instead in component and container folders. Seems like file/folder structure could be optimized quite a bit, and your proposal seems to be a good starting point.

**Comment by gretzky** [comment]
@sorenhoyer I agree. I'm gonna close this for now due to lack of attention, but feel free to fork this repo and reorganize the structure and open a PR- and we can see if that gets another discussion generated.

**Comment by migcarva** [comment]
I'm using a structure similar to what @tanichols suggested. What I found was getting on my nerves was 2 easy to fix issues.

The first was the bunch of styled-components files, which I solved by creating a` /elements` folder in every container. I did not do this for components, because they are mostly styled-components files, so were not getting mixed with reducers/actions...

The second problem was fundamentally related to mixing generic container with "pages", being the only difference between them the word `Page` in every page container... Following a similar approach to the screens' one, but not totally changing the global structure, in my containers I have only Page containers and a shared folder, where I put every container that can be shared between multiple page containers. Also, each PageContainer also have a components folder, like I did with the components/elements. This folder is where I put the components that compose the container, but are not shared between multiple containers. This cleans it a lot and simplifies the import process `import Component from './components/Component'`.
