### ISSUE TITLE
[Feature] Consider moving to Google's Workbox for offline capability?

### ISSUE THREAD

**Issue by dharmawankenny** [react-boilerplate/react-boilerplate#1880]
Hi guys, been using this boilerplate to create most of my work, and in my opinion, best boilerplate out there for client-side react.

Anyway, i've been toying around with offline capability for around 2 months now and while Webpack's offline plugin is good, but it is not as customizeable as i would prefer. And considering that Google have been releasing a great tool (albeit highly confusing at first if you try to use it by reading the docs) called [WorkboxJS](https://github.com/GoogleChrome/workbox) for 3 months now, i say we should switch to that.

It already has a Webpack plugin that pre-cache all or some of Webpack's emitted files or you can define rules on how you should pre-cache it yourself. It also comes with awesome runtime caching capability with ease. And it also comes with offline-analytics for Google Analytics.

I feel that this change would really help offline behavior and it doesn't break anything. Since it is a good feature to have i think adding this would be great, and i love what you guys are thinking about this or if there are any other great libraries for ServiceWorker there (not sw-precache and sw-toolbox, those are predecessor of Workbox).

Thanks for your awesome work guys, and sorry if i'm writing in broken english.

**Comment by developer239** [comment]
+1

**Comment by gretzky** [comment]
Feel free to open a PR that integrates this

**Comment by rajagopalx** [comment]
+1

**Comment by amankapoor** [comment]
Hi,

Just got to know through Readme.md that this project is going to have many latest features soon.
_We're working hard to get a new release out that includes React v16, Enzyme v3, Webpack v4, Redux v4, and more. ......_

I wanted to know if the new update will include workbox or not? In case no, then I suggest that maintainers please take a look at https://developers.google.com/web/tools/workbox/.

I use Workbox for my projects and it works great. I have been using it since beta stage and now with the release of v3, it has become stable.

I am willing to help anyone who can take the lead to open a PR for integrating workbox.

**Comment by gretzky** [comment]
I believe Workbox is out of scope for this bp because it's a little too opinionated of a setup. But definitely agree with forking this repo and adding it, we can add a link to it if others want it.
