### ISSUE TITLE
How to disable lint task when git commit ??

### ISSUE THREAD

**Issue by eromoe** [react-boilerplate/react-boilerplate#1895]
Hi, 

There is no document talk about this, I can't find where to disable this feature. I think such kind of features  should be recorded in the readme .

After some research, I found this
```
  "lint-staged": {
    "*.js": "lint:eslint"
  },
  "pre-commit": "lint:staged",
```

in package.json.  I remove above code, but nothing happen. 

I think it is very bad that `git`  command has been hooked without any notification or warnnings! And I even don't know where to remove this hook.

**Comment by peter-mouland** [comment]
normally, i guess depending on the linting tool, you just add `--no-verify` or `-n` to the end of the git command.

It is normal, and best practise, to have git-hooks to ensure everyone in your team are running tests on every commit and push that goes into the repo.  sometimes you just want to commit, which is why the above argument is available.

I thought RBP was using [husky](https://www.npmjs.com/package/husky), but i see they are using [pre-commit](https://www.npmjs.com/package/pre-commit).  If you have some ideas around how the docs can be improved (it's always good to get fresh eyes on these things!) i'm sure they would love a PR.

**Comment by Jonathan-Steinmann** [comment]
You should lint your code, just like you should test it also, so I like that they've included this by default.

The pre-commit file is generated from the pre-commit module that's included in your package.json.  Installing that module generates the file that can be found in the .git/hooks folder location for your project.  You could also simply change what script pre-commit runs, or if you prefer, consider creating one that only runs on a push, or runs tests and lints, etc.  Most IDEs these days will lint as you code anyway.

**Comment by KarandikarMihir** [comment]
Closing this since it's not an issue and also OP hasn't replied in a while. Feel free to continue or even re-open if need be.

**Comment by funwithtriangles** [comment]
`npm uninstall pre-commit`
