### ISSUE TITLE
using redux-thunk instead of sagas

### ISSUE THREAD

**Issue by Avi98** [react-boilerplate/react-boilerplate#1905]
# can we use redux-thunk instead of saga in this boilerplate

**Comment by Dattaya** [comment]
sure, why not. First, you'll need to remove redux-saga as [described in the docs](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/js/remove.md#removing-redux-saga), and then integrate `redux-thunk`. Do that in `app/store.js`, and that's it.

**Comment by sw-yx** [comment]
i have an alternative version of this question. can someone educate me on why redux saga was chosen over redux thunk? i am familiar with thunk and not saga. to my eyes it seems like it is because saga uses generator functions "that can be paused" and so this works well with the goal of `react-boilerplate` of being offline first. maybe this is silly because thunk might be able to do the same? thanks. i'll happily learn redux saga but i like to know a little more about the motivations behind the technical choices you have made.

**Comment by KarandikarMihir** [comment]
@sw-yx If you search in the issues section you'll find a ton of content on that :smile:

**Comment by KarandikarMihir** [comment]
@Avi98 closing since this is not an issue with RBP. Feel free to continue discussion/ask questions. Thanks!

**Comment by sw-yx** [comment]
for some reason i only got notification of this now. github is weird. thanks @KarandikarMihir
