### ISSUE TITLE
DX errors

### ISSUE THREAD

**Issue by TylerL-uxai** [react-boilerplate/react-boilerplate#1920]
Reporting usability errors as I have them to improve the developer experience.

Wasn't sure what database was included in this project. Assumed I would have to add it myself. No where in the README.md or Hitchhiker Guide does it say "database", which is what I searched (ctrl + F) the page for.

Will try to stay motivated to report more usability errors while using your project. Looks awesome!

**Comment by mjurczyk** [comment]
Not sure if including a database, or any other back-end specific features, would be reasonable for a front-end boilerplate? 
Front-end apps can be connected to various data sources, usually via an external API / WebSockets, so adding that (via `redux-saga` in this case) should probably stay a responsibility on the developers side for each project separately.

**Comment by TylerL-uxai** [comment]
Thanks @mjurczyk. Should the docs clarify this at all? Also, had a lot of trouble styling a custom component and eventually just moved the component from npm modules to the container folder. Not sure how to fix this, but I made a SO question about it https://stackoverflow.com/questions/46045746/how-to-change-the-css-on-a-component-using-styled-components

**Comment by mjurczyk** [comment]
@TylerL-uxai well, that is exactly why README suggests that this is a *really bad* repository to learn new things from (`Please note that this boilerplate is production-ready and not meant for beginners!`). And it's not there to offend anyone with less experience - simply the amount of frameworks and their combination here make it really easy to get lost in the code, unless you know what is going on.
In fact, if you clone and launch the boilerplate app example, you should get *almost* the thing that you are asking for - the example app fetches data of a user from github using redux-saga. To integrate the boilerplate with any database, you should first prepare a back-end application that serves some API endpoints for the database - and for that you will need to use either a separate framework and / or language. After you have such an API app running, all you need to do is to change the redux saga to fetch data from your API instead of Github's.
Regarding the styled components I will reply on the stackoverflow - since that is a separate topic 🙂

**Comment by TylerL-uxai** [comment]
Awesome work, MJ! Thanks for the SO response as well.

**Comment by TylerL-uxai** [comment]
Just wanted to thank you for your response again. I referenced it while building a database with the question "Where should I put the routes for server side req/res?" I see now that it should integrate with react saga. Still not sure where to put the database folder, though (if it should go in 'app' or 'server')

**Comment by TylerL-uxai** [comment]
Next DX error: unclear from documentation how to add a route with a parameter

**Comment by dalbinaco** [comment]
@TylerL-uxai Do you mean this?

https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/js/routing.md#dynamic-routes

**Comment by KarandikarMihir** [comment]
Closing this since it's not an issue with RBP (yet).
