### ISSUE TITLE
Why is there a mixture of import and require instead of all one or the other?

### ISSUE THREAD

**Issue by jeghers** [react-boilerplate/react-boilerplate#1972]
Just want to know if there is some coding style or usage issue I don't know of?  Or is this maybe just some places in code that need to "catch up" with the new ways of doing things?  :-)

**Comment by pmdarrow** [comment]
Some of the code in `internals/` and `server/` runs on Node.js that doesn't support ES6 modules & `import`, so `require` is the only option.

**Comment by jeghers** [comment]
Hmmm, I guess I don't see why Babel cannot transpile there as it does for
the rest of the code...?

**Comment by gretzky** [comment]
Not an issue. Ask on StackOverflow.

**Comment by justingreenberg** [comment]
@pmdarrow is correct... transpilation requires additional tooling, source maps etc—just to support es modules for internal scripts this would not be worth the overhead

the only time it really makes sense to run node.js code thru transpiler is to accommodate a constrained runtime environment, ie on a raspberry pi or aws lambda function... altho, even in these cases YMMV since V8 is pretty damn optimized... most apps would see better performance gains from something like https://github.com/facebook/prepack

closing, but please feel free to continue the conversation here :)
