### ISSUE TITLE
reselect usage question

### ISSUE THREAD

**Issue by bogdaniy** [react-boilerplate/react-boilerplate#1991]
ReactBoilerplate was my entry point into react world. Thank you, guys, for such amazing work. And continuing my studies, I'm wondering, why ReactBoilerplate using generators for creating selectors. 
For example:
```
const makeSelectA = () => createSelector(...)
const mapStateToProps = createStructuredSelector({ a: makeSelectA() });
```
While usage example in reselect repo is:
```
const makeSelectA = createSelector(...)
const mapStateToProps = createStructuredSelector({ a: makeSelectA });
```
Does this make any sense?

**Comment by justingreenberg** [comment]
@bogdaniy this is a great question

we create new instances of selectors when using a selector in multiple components so that each one has it's own private cache... in doing so we retain memoization and avoid triggering unnecessary renders in other components using the selector

the reason we don't need to use a factory with `createStructuredSelector` is because the composite selectors are using the factory pattern which acts as a guard

for more information on this pattern, please see [Sharing Selectors Across Multiple Components](http://redux.js.org/docs/recipes/ComputingDerivedData.html#sharing-selectors-across-multiple-components) in Redux official docs :)

**Comment by ChristianDavis** [comment]
I am not an author on this project, but the reason I follow it is that it's intended for larger scale applications. In the standard example they pass an instance of a createSelector. The hidden gotcha there is that if many components used that selector every component is now on the same selector  instance. Boilerplate uses the factory pattern here by default, so every component that gets props from makeSelectA now has it's own selector. 

Docs goes into it here https://github.com/reactjs/reselect#sharing-selectors-with-props-across-multiple-component-instances

**Comment by bogdaniy** [comment]
Thanks, went to rewrite all my selectors 👍

**Comment by justinhp** [comment]
Thank you, this was very helpful!
