### ISSUE TITLE
Glob package not listed inside package.json 

### ISSUE THREAD

**Issue by felixsanz** [react-boilerplate/react-boilerplate#2065]
Related issue: #2039 

@gretzky You're such an awful maintainer. Closing issues without even reading/understanding them. Locking issues when the conversation doesn't goes as you want. Misleading comments just to move on. Etc.

You said: " I believe glob may ship with node." <-- Wrong. That's not true. Open a nodejs REPL and check it yourself.

I took the time and effort to report something that i think it's wrong and you don't even read it. Just said "this is not a react-boilerplate issue", "I cannot replicate this", etc. Come on. You can do better than this, try harder.

cc @mxstbr

**Comment by gretzky** [comment]
@felixsanz, you did not take time and effort to fill out the issue template properly. All you stated was 'glob is imported inside internals/webpack/webpack.dev.babel.js but the dependency is not listed in package.json. Any reason for this?'. 

Not knowing the answer to something is not an issue, and nobody here is obliged to answer every question like this is a forum. It's to track issues, and glob not being listed is not an issue when it does not cause a breaking change. I then asked you to make a test repo showing that this is causing a problem, and you refused.

Feel free to contribute by respectfully following the guidelines set and then you will receive the type of response you're looking for. Don't waste Max's time because you didn't get your way.

**Comment by felixsanz** [comment]
All i stated is the entire issue. And i've filled the template properly. I'm not going to fill the Nodejs version because this is not version dependant. This is an issue inside the files.

I've already proved that `glob` is not part of nodejs and yet you refuse to find a solution for this. You forgot to discuss this in your last reply or you are not interested at all?

You asked for a test repo causing a problem. What freaking problem are you talking about? The problem itself is, again, as i stated: "DEPENDENCY NOT LISTED".

If you say "we don't care", i'm fine and i'll move on. But stop saying that it doesn't cause a breaking change, because i already know that before submitting my issue.

So another question: You just fix breaking changes? If something is not as it should be, you ignore it?

I didn't ask a question about react-boilerplate usage, i asked if there is any reason for having an unlisted dependency. I'm not going to ask inside StackOverflow because this is entirely a library design question, and i must ask the library owner not some random guy that doesn't know why it's not listed.

I hope Max or any other decent maintainer check this so we can fix something that it's not as it should be.

Thanks for closing it. Now you can lock it again to prove your point, as you're arguments are just empty.

**Comment by gretzky** [comment]
You can open a PR with the change if you'd like.

**Comment by felixsanz** [comment]
@gretzky That's precisely why my last phrase was "Any reason for this?", because i don't know if there is a reason for having an unlisted dependency. So i could know that before submitting a PR.

**Comment by gretzky** [comment]
Or, you could discover the answer through programming.

**Comment by felixsanz** [comment]
Yeah, saying that glob is provided by nodejs seems like you are doing better than me at programming.

**Comment by gretzky** [comment]
If you're better than me, answer your own question.

**Comment by felixsanz** [comment]
Can you please stop **trolling**? This isn't about who is better. **This is about an issue i reported and you're constantly bringing it down when you don't even have an answer**.

If you can't answer this, just stop it and let other maintainers give an answer. Closing issues because you can't answer them is silly.

**Comment by gretzky** [comment]
An issue tracker isn’t for posting questions. It’s for issue reporting, bug tracking, and feature discussion based on current app behavior. You posted a question, with barely any information, and didn’t follow the issue template provided either. So I closed it. That’s it.

**Comment by felixsanz** [comment]
You're so stubborn.

**Comment by mxstbr** [comment]
Relax, take a break and get some fresh air. An issue tracker isn't a shouting match.

> You're such an awful maintainer.

**@felixsanz personal attacks are way off limit**, no matter where or when. Never ever insult somebody for spending their free time maintaining free software.

Apparently people can still run the boilerplate (otherwise we would be getting hundreds of issues) so it's fairly likely a problem with your local setup @felixsanz. Can you replicate it not working on a fresh install from master? If so, the most helpful thing would be to open a PR that fixes it with an explanation of what happens. (especially when it's something small like that)

----

I really appreciate that @gretzky took the time to close hundreds of open issues, which was incredibly helpful and helps the project sustain. Obviously when doing that you're going to accidentally close some actual problems, nobody's a mastermind that can see everything.

The solution to that is never to flame them and demoralize somebody who has spent hours on triaging hundreds of questions, which is massive pain in the butt and exhausting.

**Comment by felixsanz** [comment]
@mxstbr Thanks for taking a look and "wasting" your valuable time. It's really sad that issues have to go like this, with the maintaner saying things like "you could discover the answer through programming", "answer your own question", etc. Thats also offending. So i'm in my right to question his ability to maintain the project. Calling him "awful maintainer" wasn't mean to be a personal attack, but an "attack" to his ability doing this.

About the issue, i have no problems running react-boilerplate, it works just fine. I'm just saying that there is an unlisted dependency. Isn't that an issue? I usually don't open random PRs without knowing if the change will be accepted or not. Usually people open the issue, discuss if neccesary, and then PR. Thats my flow, but obviously you're better at open-sourcing than me.

**Comment by mxstbr** [comment]
You just answered your own question, exactly as @gretzky said :wink:

> “I'm just saying that there is an unlisted dependency. Isn't that an issue?”

> “i have no problems running react-boilerplate, it works just fine.”

So no, it doesn't appear to be a problem, which makes your report a question rather than an issue with the boilerplate, which is why @gretzky (correctly) closed it with the (correct) response:

> Closing because this isn't an issue with react-boilerplate.

and later:

> The glob module is unlisted from package.json, however, I'm having no trouble running the boilerplate and any piece of it thats using glob

This is 100% the correct response: It is not an issue with the project itself (as you just said yourself), so it doesn't belong in our (overloaded) issue tracker. There is absolutely no need to escalate and throw insults @gretzky.

**Comment by felixsanz** [comment]
Ok. If you want to have an unlisted dependency i'm fine with it. No one knows why it works, but who cares. Let's move on. Thanks.

**Comment by gretzky** [comment]
Thanks @mxstbr, it's really nice to know we're on a similar page-- I never want to cross any lines while helping maintain, sometimes that's hard. Appreciate it, and thanks for having me.
