### ISSUE TITLE
RFC: Remove Immutable.js

### ISSUE THREAD

**Issue by justingreenberg** [react-boilerplate/react-boilerplate#2092]
I hope everyone had a happy and healthy holiday  🎉 back to work

So, one of the biggest complaints maintaniers hear about RBP relates to Immutable.js

There has been a lively discussion recently in #2015. People seem to be pretty split, with strong opinions both ways. The idea of this RFC is not really to evangelize one way or the other, but to start a conversation and provide a platform for maintainers and community at large to weigh in.

Give the thumbs up (👍 ) to vote to REMOVE Immutable.js
Give the thumbs down (:-1: ) to vote to KEEP Immutable.js
As well, please leave any comments below.

Thank you for taking the time to provide feedback  😄

**Comment by gretzky** [comment]
My main take on immutable is that it causes more problems than solves issues, and to me a boilerplate maintains basics (albeit some are opinionated) and immutable isn't a basic imo. I also think that any project that needs/requires it that uses this bp will be able to still re-add it back, since its been here for so long as a use case.

**Comment by blling** [comment]
I think immutable.js is great, the main problem is that we do not find the right way to use it.

**Comment by JulienMelissas** [comment]
The last two projects I've used this on I removed Immutable. The first one was because I didn't feel comfortable using it due to lack of experience. The second one was because the team decided it was not necessary. It has it's place for sure, but I think opt-in (maybe in the form of a nice guide) would be the best way to go.

**Comment by schettino** [comment]
Immutable is totally **optional**. There is a lot of discussion about get it working properly. Whereas its may be convenient to enforce best practices, developers tend to work around it just to make it work. 
Also, writing immutable states with bare metal javascript is not that bad and if you are designing your state properly, you won't find any problem here.

Removing Immutable is a great step a head if this project is about making a standard react setup, many of us just remove it on every single fresh install (I just forked this repo to stopping doing that). Just JS is fine, Immutable also is fine if you like it, and there are a tons of different helpers, including Lodash, that is already included in this boilerplate. So, please, let's get it out of here! Thanks

**Comment by ralphstodomingo** [comment]
Anecdotal: I've never had problems with Immutable. It felt like it clicks. While I'm certain things can be made to work without it, here's what the intro on RBP says, on top:

> A highly scalable, offline-first foundation with the best developer experience and a focus on performance and best practices. 

No way I'd endorse a mutable-by-default boilerplate, it is easier for me to remember everything is immutable when something breaks and the benefits outweigh the cost for me right off the bat of using RBP, but if I am to make a compromise I'd at least consider opt-in.

A framing question to the rest of us: a best practices BP is definitely not a standard react setup, since best practices can be really opinionated. Which of the two are we gearing towards?

**Comment by piuccio** [comment]
keep it, [large apps](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/introduction.md#why-all-this-fuss-just-to-load-a-list-of-repos) might not have flat objects in the store.
I already had a couple cases where components wouldn't update because people were using `PureComponents` and deep JS state.
Immutable solves the problem nicely with less cognitive bourden.

**Comment by schettino** [comment]
@piuccio on the other hand, a unexperienced usage of Immutable could trigger a lot of unnecessary re-renders. Thus, it could be more catastrophic, in a large app scenario as you say, than just write properly a shouldComponentUpdate. The problem you are reasoning about is more detectable than this one I said. Though, handle a deep JS state with immutable can add more "cognitive bourden". But if you and your team can take advantage of it, then it's fine! 

See that raising this question just show us that how it could be optional, and as the discussion here is about use it as default, I think that a guide to show the best way to add it to this boilerplate would work better for the majority. Thus, this project could ship what is really **essential** for a large app.

**Comment by trevorharwell** [comment]
I work on a large scale react application (155,937 source lines) and I personally found that I loved immutable.js in my reducers but hated it everywhere else (i.e. components).  I constantly wrestled with it until I found https://github.com/DanielBrookRoberge/reselect-immutable-helpers.  It is an incredibly simple library but it solved almost all of my frustrations with immutable.js.  Has anyone else used this library?  What has been your experience with it?

**Comment by smashercosmo** [comment]
I think that [immer](https://github.com/mweststrate/immer) could be a really good replacement for Immutable

**Comment by TreTuna** [comment]
I'm working on adopting this at my work as a starting point for our teams, however, this is one of the biggest sticking points that people are polling against using RBP. I'm digging in today to see about ripping it out (In fact, @schettino is your fork public?), and will end up maintaining a separate fork for our company due to that which is less than ideal.

**Comment by marcelorl** [comment]
I think it is fine to keep immutable, if people want a "just basic" boilerplate, they could use create-react-app. This is a boilerplate with more complete examples and nice tools to work.

**Comment by SeunghunSunmoonLee** [comment]
Meanwhile, for people who need this repo without immutable, here's the repo. 
https://github.com/Dattaya/react-boilerplate-object

Can we give two options or more? without immutable.js or with immutable.js

Discussion:
I read that maintainers of this repo saying the primary reason they used immutable was 

mxstbr 
" Ah yeah true, good point. The whole idea behind using ImmutableJS in this boilerplate was:

shouldComponentUpdate(nextProps) {
  return !this.props.equals(nextProps);
}
redux-freeze doesn't really solve that, does it?
"
They are discussing the solution here: 
https://github.com/react-boilerplate/react-boilerplate/issues/441

**Comment by liangpure** [comment]
Many project don't need immutable.js because It's heavy and need learning cost and many third ui library not support immutable.js.
It's great if immutable.js is optional.

**Comment by keul** [comment]
Sorry if I put another work on this but I fear the comment from @smashercosmo about replacing immutable with immer has not be evaluated enough. I'm a big 👍 for this suggestion.

On one of my project using react-boilerplate I removed Immutable for immer and `handleActions` approach (see https://github.com/mweststrate/immer#cool-things-built-with-immer) and:

* my reducers are a lot simpler and readable
* my bundle size has been largely reduced
* I've still a safe and immutable state management

**Comment by julienben** [comment]
I'm in favor as well personally but we don't have the manpower to work on it at the moment. (Personally, the time I can dedicate to this project is mostly spent answering issues and doing maintenance work. And @gretzky is also super busy with another RBP-related project.)

If you'd like to propose a PR for a switch to immer (using your RBP project as inspiration), I'd love to review it.

**Comment by keul** [comment]
@julienben I can try, I'm interested on keeping this project active because is a great boilerplate. But as you all, I'm pretty busy, so don't expect a PR in short term 😄

**Comment by gretzky** [comment]
Personally I still lean toward removing immutable.js entirely, and it has nothing to do with immutable.js itself, more just immutable state in general. I think immutable state needs to be a per-project, thought-out decision. For this bp it's a great showcase, but if we want to keep to one of the main goals (providing a production-ready boilerplate) then I'm more for removing it, and that might just be me taking the word 'boilerplate' and trying to remove the stigma of too much 'boilerplate code' and trying to slim down to a great starting point without users having to remove or mess with too many libs.

Sorry, that ended up being a rant. I'm always open to be convinced of a differing opinion.

**Comment by julienben** [comment]
@gretzky What do you mean by "per-project decision"? Do you have examples of projects where using an immutable state gave you issues and/or lead to a lower quality product?

I'm only asking because my intuition is that immutable state is always better than mutable state but my intuition is stupid and she makes mistakes all the time.

**Comment by gretzky** [comment]
@julienben sure, when you utilize a boilerplate to build microservices / micro-apps inside of a larger application, immutable state can get super wacky when integrating, because you have to make absolutely sure that your state tree is 100% immutable, or else it throws an error. that's my only qualm really, when you rely on boilerplates because you're spinning multiple services up with them to integrate in a larger app- there's so much more room for error there, esp. in the case of immutable- which has its own special package spinoffs (redux-immutable, etc.) and must be _exact_ in order to not only work, but also follow the philosophy of microservices and state trees together

**Comment by julienben** [comment]
I didn't follow you entirely. You've used RBP to build "micro-apps"? Which you then load inside iframes in a larger app? Or actually, if it's an iframe, how do you share state? And if not iframes, how do you load multiple "micro-apps" into one page? You've piqued my curiosity now... 😅

I'm definitely not married to the idea of immutable state but I do like some of the protections inherent to it. For example, if one isn't super familiar with deep vs shallow cloning and might accidentally copy objects by ref instead of value. 

It also simplifies your ability to do updates deep in the state (using setIn()). You can also do it with react's immutability-helpers but that's still an additional library to learn.

I wonder if there's yet another solution which could protect the dev from accidentally mutating state.

**Comment by nagyv** [comment]
I would suggest either removing or replacing immutable. It's an extra burden for those who don't need it, and it makes adoption harder for those who don't know it. 

For the latter problem, a really convenient solution is to use [seamless-immutable](https://github.com/rtfeldman/seamless-immutable). As it's much more in line with usual JS syntax, you would use this syntax anyway.

**Comment by gretzky** [comment]
Yup @justingreenberg, that's exactly what I do.

Tbh I think one of the easiest immutability checkers in development is typechecking with Flow. It works incredibly well in combo with reselect. It may not be as in-depth as an immutable library or other invariant library, but it does work well for me in development and production without having env-specific libs or middlewares.

**Comment by zongwan** [comment]
seamless-immutable ???

**Comment by markerikson** [comment]
I'll mention that the Redux team has been putting together a small library called [`redux-starter-kit`](https://github.com/reduxjs/redux-starter-kit), which includes a `createReducer()` utility that uses [`immer`](https://github.com/mweststrate/immer/) internally.  I've always [recommended against using Immutable.js for several reasons](https://www.reddit.com/r/javascript/comments/4rcqpx/dan_abramov_redux_is_not_an_architecture_or/d51g4k4?context=3), but I highly recommend using Immer.

**Comment by sag1v** [comment]
@markerikson How is immer solving the problems you mentioned in the post you linked to.

**Comment by markerikson** [comment]
- Immer works on plain JS objects, so you don't have to convert back and forth between Immutable.js Maps/Lists and plain JS objects/arrays
- Similarly, you can still spread and destructure POJOs, rather than having to call `.getIn()`
- Immer simplifies immutable update logic.  Updates to objects can be written as standard "mutative" code, like `state.someObject.someArray[5].value = 123`

**Comment by sag1v** [comment]
@markerikson it is better indeed.
Though if someone that new to a repo and dosn't know immer is implemented he/she could think this is mutation. I mean when the syntax is the same its less obvious that this is not mutating the data and may confuse others. 
Quite a dilemma

**Comment by markerikson** [comment]
Yep, that _is_ the one downside with Immer, and I don't have a good solution for that yet.

**Comment by julienben** [comment]
Might be feasible with a custom ESLint rule, no? I'd be happy to give it a shot.

**Comment by csantiago132** [comment]
Well, I’d say that thanks to this boilerplate, I learned immutable.js, other than “get.()” and “set.()” I don’t see a reason to take it out. I agree that for some projects it might not be needed, but most of them would benefit from it and have it ready to go

**Comment by sag1v** [comment]
Call me crazy but i prefer the built-in methods that comes with the language and less abstraction in this case. We have destructuring, filtering, mapping, slicing, reducing etc... these are great times for javascript. Yes, you may write extra code but it is one less dependency to worry about and less syntax / pattern to teach others. i think the closest you get to the language is better for the long run.

**Comment by StevenLangbroek** [comment]
So, I understand I'm late but I'd like to chip in. I've used ImmutableJS at 3 jobs:

1. Greenfield project where I controlled the stack. I too was drawn in by the promise of, you know, free immutability and (close to) functional lenses.
2. Engineering company of 100 people, mixed skill level
3. Current job, about 15 (front-end) engineers working on this codebase I guess

I've had extremely mixed results at all of these. To the point where I would not recommend it without careful evaluation and tireless advocacy. What I failed to notice is that while yes, there are cases where ImmutableJS offers performance improvements, there are serious drawbacks:

* **SerDe boundary:** When you're shipping between server & client, you have to `.fromJS()` and `.toJS()`. This operation is costly and synchronous, so it could really hurt performance, especially on high-traffic websites where large requests can drown out smaller ones.
* **High potential for perf gotcha's:** You might be inclined to start throwing `PureComponent` at everything. But do you fully understand all the other moving parts of your application, also injecting their props, handlers etc? You can easily carry over assumptions about identity equality, causing very expensive reconciliations in unexpected places. Debugging these situations can be finnicky. Even worse is they might run fine on our high-end Macbook's, iPhones and Pixels, but can *seriously* hurt performance on lower-end devices. It can make your app unusable on "potato-phones" (e.g., sub $75 Android devices).
* **Spread:** you don't fully appreciate how much you use arrays and objects until you swap them out with something else, and let me tell you, ImmutableJS can *easily* get all over your codebase, making it nearly impossible to get rid of without a structured approach and manual QA.

If you add all this up, and then measure and see that the perf benefits are decidedly "meh" for 80 - 90% of your use-cases, it's just not worth it. And I think for 90% of developers, that's the case. There are legitimate performance concerns that React developers will face, and I think this one is a bit of a McGuffin. 

- If you have nested data that needs to be updated without mutating too much, your real problem is probably your state design, which you should address first. 
- If you still have trouble dealing with mutability, look into helpers like immer, or take the functional, lens-based approach that your team is now familiar with anyway. I'll give ImmutableJS that, they've made people excited about Profunctor Optics ¯\_(ツ)_/¯.

**Comment by StevenLangbroek** [comment]
Regardless of what you all decide, I wouldn't mind contributing documentation on how to deal with tricky states, in either Immutable or using a functional approach. I'm writing this anyway :)

**Comment by StevenLangbroek** [comment]
(I think at the time we reduced its footprint with a `pure(...propKeys)` HoC, which took care of `shouldComponentUpdate` and `toJS()`ing so that you're not fidgetting with getters etc. in your components).

**Comment by markerikson** [comment]
@StevenLangbroek : thanks for the feedback!  It actually is very similar to my opinions in the comment I linked above.  But, I've never actually worked with Immutable.js directly myself, so it's good to A) have feedback from someone who has used it, and B) see that the concerns I'd expressed are somewhat validated by real-world experience.

**Comment by StevenLangbroek** [comment]
Also a potential minefield is if you want your root reducer to be an Immutable Collection is you end up with this explosion of glue-dependencies and boundaries, not unlike what we used to have with `grunt`. It can cause unnecessary delays in dependency updates, bug fixes that are slow to propagate etc.

**Comment by outdooricon** [comment]
Throwing in my two cents here, but I think the way that immutable works with reselect is a perfect union. With ImmutableJS's structured sharing, reselect functions are saved a lot of runs since a lot of the immutable data will pass the equality check. I've created a fair share of apps and teams around this stack and have had great success.

See https://medium.com/@dtinth/immutable-js-persistent-data-structures-and-structural-sharing-6d163fbd73d2 for more info on Structural Sharing

**Comment by Tyak99** [comment]
Please i need someone to  walk me through removing immutableJS from the boilerplate. The steps should be put in the remove.md. The boilerplate is great but i think the only problem is immutableJS. Such abstraction should be optional in my opinion

**Comment by Tyak99** [comment]
@Absvep Thank you! I came across the repo without immutableJS. unfortunately it was created 2015, alot has changed since then. An example is It not being updated to react 16. To use it now one will need to put in extra work. I guess i'm stuck with using ImmutableJs in my project

**Comment by julienben** [comment]
Check out #2380. It uses immer instead of immutable. I highly recommend immer. But if you don't want it, the branch should at least help you understand how you could remove immutable in your project.

**Comment by Tyak99** [comment]
@julienben Thank you very much, it was helpful. I have been able to remove immutableJS from my project.

**Comment by danielo515** [comment]
To be honest, I don't understand why many of developers using react have the need to use libraries specific for React or coming from the react team. There are dozens of libraries for accessing objects in an immutable fashion, with high performance and without any lock in. Take partial.lenses as an example. It does not have redux or react+dash+whatever on his name, but it is a great optis library for accessing and mutating deep object structures on an immutable way and with great performance. I don't see the benefit on immutable, it requires too much commitment to it, and libraries should not require so much from you. If you are going to tie your entire code ass for gaining such safety you are probably better going to a language with that phylosophy like Elm, Reason, purescript...

**Comment by julienben** [comment]
Closing this as the next version of the boilerplate will include immer.
