### ISSUE TITLE
npm start with https

### ISSUE THREAD

**Issue by andreas-koch** [react-boilerplate/react-boilerplate#2107]
Hi,

is it somehow possible to start the dev mode of the boilerplate with https enabled?

Thanks,
Andreas

**Comment by Droow** [comment]
Not sure if it is possible via RBP alone, but I use nginx even in development because I need to have backend and frontend on the same URL like "myproject.dev" and "myproject.dev/api" or "api.myproject.dev" and in the nginx configuration I have SSL enabled and then I send these request as a proxy to 127.0.0.1:3000 for frontend and to different port for /api and it works perfectly.

**Comment by andreas-koch** [comment]
Thanks for the hint. I did setup nginx and it works.

**Comment by Dmitry-N-Medvedev** [comment]
@andreas-koch, does HMR work in your configuration?

when I change a project file I can see `[HMR] bundle rebuilding` in the browser's console. But no refresh happens.

**Comment by Dmitry-N-Medvedev** [comment]
For all who is struggling to make HMR work behind NGINX here's my config:

```
  location /__webpack_hmr {
    add_header Access-Control-Allow-Origin https://development.dmx;
    proxy_set_header Connection '';
    proxy_http_version 1.1;
    chunked_transfer_encoding off;
    proxy_buffering off;
    proxy_cache off;
    proxy_pass http://devlocal3000/__webpack_hmr;
  }

```
Source: https://stackoverflow.com/a/13673298/743045

**Comment by juanpmarin** [comment]
Hi @andreas-koch, how is going ? 
Can you share your setup please ? I'm new with nginx and I would like some example to start
