### ISSUE TITLE
proposal: remove the ignore-pattern flag for eslint

### ISSUE THREAD

**Issue by joggienl** [react-boilerplate/react-boilerplate#2159]
I noticed the `--ignore-pattern` flag being set to ignore all files under internals/script.
This made me wonder: why has this path been excluded in the past, does anyone know that?

I found out that this PR changed it: https://github.com/react-boilerplate/react-boilerplate/pull/417.

I would like to suggest to remove this flag from the package.json `lint:eslint` script. This way all code gets proper lint information and improve quality overall, especially of these scripts. This does imply that there needs to be some fixes on the code in there at the moment, but that shouldn't be that dramatic I hope.

As also per contribution guidelines I wanted to get input on this before submitting anything ;-)

**Comment by gretzky** [comment]
Hey @joggienl, thanks. `internals` are excluded because they're just code for making this boilerplate run and have no effect on linting your _actual_ project code. it'd be unnecessary to lint them every single time because the intention is that they should never change, and only be used to have the boilerplate run seamlessly.

**Comment by joggienl** [comment]
Hey @gretzky, thanks for your response!

I noticed I do feel somewhat strong against your argument. I will try to give some thoughts I have.

So, I do think it adds value. For starters, the overall quality of the boilerplate improves. When you run eslint now on the internals folders, you get all kinds of errors and warnings. Just as the whole project, as user I would expect the same quality of code there as elsewhere. At this point it _feels_ like these files are not being linted and that is bad. But, again, that is how it feels.

If you would never change anything in the internals folder, it _could_ make sense to lint them every time. So I can agree somewhat here. As a side note, its not that much code so it would not hurt in terms of performance.

If you clone/fork the project you could have at least two reasons for that: either you are going to start on a new cool project and want to use this fancy awesome boilerplate, or, you want to contribute on this awesome boilerplate. For this last option the argument of "it is internal" does not count. Then it should get linted.

Also, from personal experience, I do change things in my externals folder! That's the beauty of this project. It does a lot of cool things under the hood, but can be easily changed to meet your (new) requirements.

So, what if _everything_ would be linted by default? It might be possible to change this behaviour as soon as you run the setup or clean script (that probably means you are going to create something with the boilerplate). And by that I mean that the ignore path can be put to the script at that moment. Or maybe use the more common `.eslintignore` file for that. But even then I would like that to be optionally asked to me as user.

Curious!

I have some more thoughts on the eslint part of this project. But I wanted to discuss this one first :-).

**Comment by joggienl** [comment]
Oh, I was also wondering, is there a particular reason why the issue immediately gets closed after response?

**Comment by gretzky** [comment]
@joggienl, I closed this issue right after commenting because my comment is a direct reflection on the choices made for this boilerplate.

There is no reason to run eslint on the internals folder unless you're developing directly for the boilerplate. None of that code should be affecting your projects code at all, therefore there is no need to lint it. The boilerplate code in internals is written specifically for the boilerplate. If you find it needs linting, then I suggest opening a PR with the linted code.

If you find you're linting the internals folder often, you can easily add the folder to the `eslint/` script in `package.json`. Otherwise, again, this boilerplate is just that- a bp, and the bp specific code shouldn't need to be linted unless you're working on this bp. It doesn't make much sense otherwise. If you still feel strongly, you can open a new RFC issue to get others perspectives.
