### ISSUE TITLE
Updating to React 16

### ISSUE THREAD

**Issue by vester-the-developer** [react-boilerplate/react-boilerplate#2200]
I ran into an issue getting jest-styled-components to work with enzyme-to-json. I found out the issue was due to not having the latest version of enzyme and with upgrading that I noticed that I needed React 16 and so forth and so on.  Can someone walk a noobie through upgrading dependencies without breaking everything?

**Comment by gretzky** [comment]
Hey @vester-the-developer, you can checkout the dev branch of this bp and see how we've implemented upgrades so far

**Comment by Stupidism** [comment]
@gretzky When will this be released?

**Comment by julienben** [comment]
@Stupidism Please don't ask for ETAs. There are none.

**Comment by Stupidism** [comment]
@julienben What's ETA? 
Can somebody explain a little longer about why react@16 was released in Sep 2017, but this repo is using react@15 in master branch in May 2018?

Should I use dev branch directly?

**Comment by gretzky** [comment]
@Stupidism, this repo is maintained by a couple of people who spend their free time on it. It's open source, we aren't paid, and unfortunately we all do have jobs that spread us thin when it comes to getting updates out. 

Some updates, like react 16, come with other updates-- in this case, updating react means we need to update Enzyme- and there are some outstanding issues with Enzyme v3 that we're waiting to clear. If we don't wait for those to clear, we either force users to deal with errors or we rewrite all of the unit tests in this bp.

Another piece that is often not talked about are the politics of maintaining a boilerplate. There are a lot of opinions from both maintainers and users, and we're always trying to make sure we're striking a delicate balance. This can lead to slower release times. This doesn't really apply to react 16, but I wanted to just throw it out there since I feel sometimes it isn't talked about.

As it stands, @julienben and I are really the only ones around with a couple of others who are in and out-- and personally, I think that's fine. We've had an open call for maintainers, and if anyone wishes to contribute they can. But I do feel that once a maintainer is on the inside, they see why it takes time. We're doing all we can with the resources we have.

To be clear about my personal situation, I'm the lead engineer at a startup and my Q2 goal was to grow out my team AND release a major version release of the app I build. What I'm trying to say is that my own work gets busy, and so I have less time to devote. Such is the same for many of the maintainers here. And yes, I do use this bp at work as well, so I know it's critical that it be updated soon.

I would say to use the dev branch directly at this point. I'm hopefully coming up soon on some time I can dedicate here to cleaning up and doing incremental updates to the master branch. There are a lot of dependencies that have to be updated, so this takes time. The JS ecosystem is, dare I say, the fastest moving software ecosystem right now. 

I know it's frustrating that we don't have what seems like a very basic yet extremely important update out. Please bare with us while we get things out, @julienben is right in saying to not ask for ETAs only because it's also really hard on us as well to keep answering the same questions over and over. 

I hope this can shed some light on everything.

**Comment by julienben** [comment]
Very good response. We should save it for future use.

@Stupidism ETA = Estimate Time of Arrival although I really think you ought to be able to Google that for yourself.

**Comment by Stupidism** [comment]
@gretzky Thank you very much for your explanation and your patience. 
Sorry, I didn't mean to be rude. I was new to this bp, cloned it and started my little project. Then I was surprised that it's still using react@15 and the only issue for react@16 was proposed one day ago. I was confused why the issue was closed so quickly and the response looked not helpful to a new bee who is not familiar with this bp at all.

@julienben Thanks to my poor English, I didn't succeed to match any of the definitions in wiki when I Googled it, not until seeing your response.

**Comment by gretzky** [comment]
@Stupidism no problem, thanks for taking the time to read my response. Many people have asked that question, and personally I never gave a full thorough answer-- so you helped me out by calling that out! Thank you for understanding.

**Comment by julienben** [comment]
@vester-the-developer New version 3.6 is out with React 16 and more.
