### ISSUE TITLE
Is there a sample app to automatically create a sitemap during deployment?

### ISSUE THREAD

**Issue by nahankid** [react-boilerplate/react-boilerplate#2203]
I believe generating a sitemap should be a standard feature of this great boilerplate. Is there a sample?

**Comment by gretzky** [comment]
Good suggestion! I don't think we'll be adding a sitemap to this boilerplate natively, only because some people will use this bp for an app (which may not require a sitemap) and they take time to setup properly. I suggest integrating (sitemap.js)[https://github.com/ekalinin/sitemap.js] into your project.
