### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by diegohdez90** [react-boilerplate/react-boilerplate#2279]
I was developing with `exceljs` to export json to *.xls excel format, but when webpack update via console display this message

```
Module not found: Error: Can't resolve 'fs'
```

in multiple react-boilerplate dependencies

I try to update dll file with 

```
$ npm run build:dll
```

when finished to build it, console displays `fs` errors in many package dependencies.

Then I tried delete `./node_modules` directory and then `$ npm i` to install my dependencies and again display all `fs` errors messages.

someone have any idead what happen or is `exceljs` dependency the error?

Thanks.

**Comment by michaelcuneo** [comment]
It's irrelevant and your project will run perfectly fine without it. fs is for an underlying feature of exceljs and many other nodeJS modules that don't work inside a React.JS App. If you need to make the error go away because you're sick of looking at it... 

Go to webpack.base.babel.js inside /internals/webpack ... 

And add somewhere close to the bottom... mines directly above devtool: options.devtool ... 

node: { fs: 'empty' },

This will cause the webpack to ignore fs dependencies.

i.e. 

```
  resolve: {
    modules: ['app', 'node_modules'],
    extensions: [
      '.js',
      '.jsx',
      '.react.js',
    ],
    mainFields: [
      'browser',
      'jsnext:main',
      'main',
    ],
  },
  node: { fs: 'empty' },
  devtool: options.devtool,
  target: 'web', // Make web variables accessible to webpack, e.g. window
  performance: options.performance || {},
});
```

**Comment by julienben** [comment]
You can also find some comments on this topic directly in the ExcelJS repo: https://github.com/guyonroche/exceljs/issues/299 and https://github.com/guyonroche/exceljs/issues/606

**Comment by diegohdez90** [comment]
Wow, Thank you very much @michaelcuneo & @julienben.

Keep coding.

**Comment by julienben** [comment]
🤟

**Comment by MehrnooshHajkhalil** [comment]
I found a way for this issue [here](https://stackoverflow.com/questions/51694902/react-boilerplate-error-cant-resolve-xlsx-in-users-react-boilerplate-no) that might be useful
