### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by PauloBarbeiro** [react-boilerplate/react-boilerplate#2283]
Hello all,

I found a problem while trying to use Auth0.js (v.9.7.2) library. It is a problem with Babel transpiler. The issue has caused different errors, and I believe this would happen with new libraries start to adopt the new JS conventions by default.

## Test Watcher
As soon as I imported the library in the App container, the test:watch show the SyntaxError: Unexpected token import.

In the image bellow, I pointed out the import in the code, and the error in terminal.
![selection_002](https://user-images.githubusercontent.com/3474608/42942062-0e7e24c0-8b5f-11e8-8e91-fca73a2d6779.png)

## Test
After that error I tried to check how the test would behave.
The simple import did not cause the same error, only a warning that auth0 was not been used.
Then I decide to create a new Singleton Object for test purposes. The class was created in a new folder called helpers like app > helpers > AuthService.js
With this code:
![screenshot from 2018-07-19 15-49-33](https://user-images.githubusercontent.com/3474608/42946566-7a155bac-8b6b-11e8-8bf5-f761d39dc235.png)

Till that point the I just got some error that some lines had no test coverage. But when I import the class to the App.js container, the **SyntaxError: Unexpected token import** happened again.
![selection_003](https://user-images.githubusercontent.com/3474608/42946032-3e69f58c-8b6a-11e8-844c-42b31aa42a71.png)

It is relevant to say that the error in the test did not impact the webpack server, and the app were running fine in the browser.

So far my attempts to solve the issue was not successful. How it is possible to fix this?

## Steps to reproduce
- Brand new React-boilerplate
- npm i auth0-js --save
- import the auth0 library some where in the code: import auth0 from 'auth0-js';
- npm run test:watch

## Versions
- React-Boilerplate: 3.6.0
- Node: 8.9.3
- NPM: 5.5.1
- Auth0-js: 9.7.2

**Comment by julienben** [comment]
I get the same issue as you if I use auth0-js 9.7.2 but not if I go back a few versions (tried 9.6.0). It turns out they migrated to ES modules 16 days ago.

If you look at the auth0 code in your screenshot (from auth0-js/src/index.js:1) you'll see it's not valid JS as it mixes ES modules with CommonJS syntax (if I'm not mistaken) so they must be doing something a little unconventional in their build.

I also played around with our jest and babel setups and tried switching to babel-jest. None of it worked. This is probably something that can be fixed by the auth0-js team only.

**Comment by julienben** [comment]
Closing this as there's nothing we can do about it from here but please reference this issue if you submit one to the auth0-js team.
