### ISSUE TITLE
React Boilerplate Electron Version

### ISSUE THREAD

**Issue by mjangir** [react-boilerplate/react-boilerplate#2288]
This is really not an issue but, I had no idea where to put this. I searched a lot for turning this awesome boilerplate into electron application and finally decided to do changes at my own:

For people:

**Who want to add electron support in their existing application:**
[https://medium.com/@mjangir70/turn-the-famous-react-boilerplate-into-electron-desktop-application-68d91dce8d3a](https://medium.com/@mjangir70/turn-the-famous-react-boilerplate-into-electron-desktop-application-68d91dce8d3a)

**Comment by gretzky** [comment]
Awesome, @mjangir! Great write up. Normally we like to keep this issue channel clean, but I think I'll leave this here for a little bit since it is a great write up and hopefully more people will see it. 

If you want to, feel free to open a PR and include a link to this post in the docs somewhere! Also, feel free to post about it on [Spectrum!](https://spectrum.chat/react-boilerplate).

**Comment by julienben** [comment]
Yup in the long term the best way to do this is probably via a link in the docs.

**Comment by xeoneux** [comment]
I was looking exactly for this! Please add it to the docs 😃

**Comment by mjangir** [comment]
Added complete documentation on creating an electron desktop application out of this boilerplate. Just raised a pull request for that. Kindly review.

**Comment by gretzky** [comment]
Thank you @mjangir!
