### ISSUE TITLE
fs.existsSync(path) should cause error

### ISSUE THREAD

**Issue by Eugene-Musika** [react-boilerplate/react-boilerplate#2343]
In [webpack.dev.babel.js](https://github.com/react-boilerplate/react-boilerplate/blob/master/internals/webpack/webpack.dev.babel.js) you have next code:

```javascript
const fs = require('fs');
const path = require('path');
...
function dependencyHandlers () {
...
    return dllManifests.map(manifestPath => {
        if (!fs.existsSync(path)) {  
            if (!fs.existsSync(manifestPath)) {
/* 
Error!
Cannot call `fs.existsSync` with `path` bound to `path` 
because module `path` is incompatible with string
*/ 
```

I think you should delete line with `if (!fs.existsSync(path)) {`

**Comment by gretzky** [comment]
Please fill out the issue template. I'm not sure what any of this means.

**Comment by Eugene-Musika** [comment]
It means, that there is mistape in webpack config for Dev mode.

**Comment by julienben** [comment]
There could be a bug in `webpack.dev.babel.js` but none of the boilerplate's many contributors and users noticed it so it must specific to your setup. You need to provide precise steps allowing us to reproduce the error so we can understand it. Please base yourself on the [Issue Template](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/ISSUE_TEMPLATE.md). We're unable to help otherwise.
