### ISSUE TITLE
when using feathers express, it gives page not found error #2355

### ISSUE THREAD

**Issue by SeunghunSunmoonLee** [react-boilerplate/react-boilerplate#2359]
1. I believe this must be addressed considering both react-boilerplate and feathers are extremely well known and they go together often in development process.

2. React-boilerplate docs can explain how to modify the backend without causing the issue. Or at least a guide where to look at. 
I think I am asking the right thing. Therefore, I'm reopening this issue.

_Originally posted by @SeunghunSunmoonLee in https://github.com/react-boilerplate/react-boilerplate/issue_comments#issuecomment-425859978_

**Comment by gretzky** [comment]
Sorry, I don't agree. Just because Feathers is popular doesn't mean that react-boilerplate is required to support it or have documentation on it. You could open this same issue on Feathers and just reverse the names. 

Closing as this is not an issue for react-boilerplate as we don't support feathers out of the box. 

That being said, we'd be open to checking out a PR for adding documentation

**Comment by julienben** [comment]
Nobody here is entitled to "ask" for anything. If you have an idea for an improvement, you may suggest it politely or even take it upon yourself and contribute with a pull request. Anything else is disrespectful and not aligned with the principles of open-source development.
