### ISSUE TITLE
Development experience is poor due to the slow HMR. Or is there any mistake I'm making?

### ISSUE THREAD

**Issue by SeunghunSunmoonLee** [react-boilerplate/react-boilerplate#2364]
## Steps to reproduce
Development experience is poor due to the slow HMR. Or is there any mistake I'm making?
Thanks
https://github.com/SeunghunSunmoonLee/React.ai

# Versions

- React-Boilerplate (see `package.json`):
- Node/NPM: latest stable
- Browser: chrome

**Comment by gretzky** [comment]
I'm sorry, I can see that you're frustrated with this boilerplate in the numerous issues you've opened. The people who maintain this repo do so for free, and we have day jobs and lives that can sometimes hinder our focus on open source projects.

Closing because this isn't an issue and the issue template was not filled out properly. How am I supposed to address an issue that juts says 'HMR is bad'?
