### ISSUE TITLE
Postinstall - build:dll - wrong path creation for react-boilerplate-dlls folder

### ISSUE THREAD

**Issue by Bastek333** [react-boilerplate/react-boilerplate#2378]
## Issue Type

Bug

## Description

Postinstall script which is running build:dll with node ./internals/scripts/dependencies.js is throwing an error - as path for creating appropriate folder is wrong. This is only on development environment as on production this script is skipped !!! 

> aem-authoring-ui@1.0.0 build:dll C:\Projekt\aem-dc-view-spike
> node ./internals/scripts/dependencies.js

mkdir: cannot create directory **C:/Projekt/aem-dc-view-spike/C:/Projekt/node_modules/react-boilerplate-dlls**: Not a directory
Building the Webpack DLL...
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);

**And I did quick checking:**

**dllConfig:**  { [Boolean: false]
  exclude:
   [ 'chalk',
     'compression',
     'cross-env',
     'express',
     'ip',
     'minimist',
     'sanitize.css',
     'react-icons',
     '@opuscapita' ],
  include: [ 'core-js', 'eventsource-polyfill', 'babel-polyfill', 'lodash' ],
  path: 'C:\\Projekt\\node_modules\\react-boilerplate-dlls' }
**outputPath:**  C:\Projekt\aem-dc-view-spike\C:\Projekt\node_modules\react-boilerplate-dlls
**dllManifestPath:**  C:\Projekt\aem-dc-view-spike\C:\Projekt\node_modules\react-boilerplate-dlls\package.json

## Steps to reproduce
 just npm install - or 
node ./internals/scripts/dependencies.js

# Versions

- React-Boilerplate (see `package.json`): "version": "1.0.0"
- Node/NPM: 6.4.1

**Comment by julienben** [comment]
Thanks for filling in the issue template!

I'm afraid I can't reproduce your error though. (We have lots of automated testing so if `npm install` were failing for everyone, it would have been noticed right away.)

This is most likley due to an "incompatibility" between your computer setup and this project. The result is that your output path for the dll file is broken (since `C:\` is repeated twice).

Let's see if we can fix it!

On your computer, could you open `dependencies.js` inside of `internals/scripts/` and replace all three instances of `path.join` with `path.resolve`?

Then rerun `npm install` and report back.

**Comment by Bastek333** [comment]
Thank you for quick answer.

Looks like path.resolve has resolved issue :) - now the script is running fine.

If it will not break the script for others will suggest to replace it as well in boilerplate :)

Regards

**Comment by julienben** [comment]
Thanks! Suggesting it in a PR right now.
