### ISSUE TITLE
Addition of a solid Redux-persist rehydration implementation in the next release?

### ISSUE THREAD

**Issue by michaelcuneo** [react-boilerplate/react-boilerplate#2389]
This is not an issue, but a question to ask if anyone would like to see my implementation of redux-persist PR'd into the next version of RB?

I've found that nearly every project I've done using react-boilerplate, my first change before doing anything, is adding my redux-persist implementation, so people can still use back and forward without data being dropped around all over the place.

I don't know if other people see this to be a huge benefit, but I use it in every project.

Let me know if anyone would find this useful, and I'll push it up.

To summarise it's ease of implementation, the only changes needed to configureStore.js are as follows... 

```
import { persistStore, autoRehydrate } from 'redux-persist-immutable';
import { localForage } from 'localforage';
import { REHYDRATE } from 'redux-persist-immutable/constants';
import createActionBuffer from 'redux-action-buffer';
```

const middleWares becomes...

```
  const middlewares = [
    sagaMiddleware,
    routerMiddleware(history),
    createActionBuffer(REHYDRATE),
    // createLogger(),
  ];

```

const store is changed to 

```
  const store = autoRehydrate({ log: false })(createStore)(createReducer(), fromJS(initialState), composeEnhancers(...enhancers));
```

and persistStore is added to configureStore.js

`persistStore(store, { blacklist: ['route'], storage: localForage });`

Everything else stays the same... and it works perfectly.

**Comment by satishjhanwer** [comment]
@michaelcuneo I have done similar look at [here ](https://github.com/react-boilerplate/react-boilerplate/issues/2294#issuecomment-411012258)

**Comment by michaelcuneo** [comment]
@satishjhanwer Yes, it's only a few lines of code to add a solid rehydration method. I find it essential in every project.

**Comment by michaelcuneo** [comment]
But then we have to consider that immutable is being replaced in the new version, and redux might be leaving as well? Hard to tell what the complexity or ease of this will bring.

**Comment by julienben** [comment]
Immutable is probably staying for at least one more release since there's been no consensus as to what it should be replaced with. As for redux, what makes you think it's leaving? I'm not aware of any such plan.

Regarding redux-persist, my personal opinion is that it's maybe not something that we should impose on every RBP-based project but it would make a lot of sense in our list of forks. See [here](https://github.com/react-boilerplate/react-boilerplate/tree/dev/docs/forks). We already have Electron, SSR, and Typescript.

In the long run, I'd love to see the list of forks become more of a group of instructions for people who want to add SSR, TS, Electron support, redux-persist, etc. The same way that we have instructions for removal of I18n and other stuff. It would probably be cleaner than links to external repos which might not all be maintained...
