### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by muthukumarse** [react-boilerplate/react-boilerplate#2395]
Can we use this project to React Native?

We developed a project based on react-boilerplate. So we are very much comfortable all the dependencies. We are planning the same project into Mobile with minimum functionality. 

How we can get start React Native based on react-boilerplate

any suggestion similar too, please do let me know.

**Comment by Kamran1122** [comment]
Same request.

**Comment by joshuaalpuerto** [comment]
Hi there, I don't know if this is relevant but I think this is worth mentioning. I've used [Ignite](https://github.com/infinitered/ignite) boilerplate specifically their [andross](https://github.com/infinitered/ignite-ir-boilerplate-andross) template. The setup is really similar as of this, it has immutable(`seamless-immutable`), redux and redux-saga. I added `reselect` my self w/c is pretty straightforward to implement. Plus it also has their own generators so jumping to it is not hard.

Let me know your thoughts

**Comment by muthukumarse** [comment]
@joshuaalpuerto thanks for your suggestion.

we planning to convert into mobile of the project which we developed based on react-boilerplate.

**Comment by michaelcuneo** [comment]
Because React-Native relies on a tonne of other components that are relevant to RN, the entire component section would need to be converted to RN based code... you could just run both codebases side by side and have something wrap and select based on the use case, but there's a lot of problems with it. Unless the project is massive like Facebook, the amount of trouble isn't worth it.

After you understand the way this Boilerplate works, it's very easy to implement most of the same functionality without a problem. i.e. sagas, redux, router 4, reducers, actions, ... etc.

**Comment by julienben** [comment]
Hey all, gonna close this as there isn't anything to be done here. Please search the closed issues for more discussions on this topic.

That being said, if you end up implementing a fork with React Native support, we'd be happy to see it and maybe link to it from the docs.
