### ISSUE TITLE
Suggestion -> redux-first-history 

### ISSUE THREAD

**Issue by salvoravida** [react-boilerplate/react-boilerplate#2422]
# React Boilerplate

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

Please direct redux-saga related questions to stack overflow:
http://stackoverflow.com/questions/tagged/redux-saga

For questions related to the boilerplate itself, you can also find answers on our gitter chat:
https://gitter.im/mxstbr/react-boilerplate

**Before opening a new issue, you may find an answer in already closed issues**:
https://github.com/react-boilerplate/react-boilerplate/issues?q=is%3Aissue+is%3Aclosed

## Issue Type

- [ ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md#feature-requests)

## Description
redux-first-history -> one way in react-router and @reach/router

https://github.com/salvoravida/redux-first-history

Maybe it could be usefull to users that need only one source of truth.

it should improve performance.

I look forward to receiving your feedback.
Regards.
Salvo

**Comment by mjhost** [comment]
Hi salvo, as per #2420 you may have a better welcome if you use the template.

**Comment by salvoravida** [comment]
@mjhost done.

**Comment by julienben** [comment]
Hey @salvoravida, Thanks a lot for the suggestion!

I have to say it would've been nice if you could've described in slightly more details how this could improve `react-boilerplate`. Not everyone has time to dig in to the README of a brand new project...

In any case, this seems cool and potentially useful but my personal opinion is that we shouldn't be adding this because:
1. it would mean an extra dependency in an already complex setup,
2. it's not necessarily relevant to every user of the boilerplate (+ I've personally never had an issue with receiving different histories or locations),
3. it's not immediately clear what your library does,
4. thus it increases the learning curve of the project,
5. it's brand-new and hasn't been tested at a large scale.

Happy to be convinced by any maintainer who thinks differently!

Cheers

**Comment by salvoravida** [comment]
hi @julienben 

i will try to get your point:
1) it's not an extra dependency, it will replace connected-react-router
2) it should improve performance, because of correct one-way-dataflow and no extra React Wrapper
moreover it should resolve tons of issue like these: 
https://github.com/supasate/connected-react-router/issues/168
https://github.com/supasate/connected-react-router/issues/177
https://github.com/supasate/connected-react-router/issues/126
that are all related to wrong way of sync history in React-comp, that does not garantee a one way data flow, like redux-first-history.
(this is way i think redux-first-history while i was working on a large project with same issue as above)

3) it's an alternative to "connected-react-router" and "react-router-redux" that NOT violate first Redux principle : one store - one way data flow.

4) i do not think so, it's just a one-time configuration middleware for redux. users do not care if already integrated into the boilerplate

5) Yes you are right, it's a brand new lib ... i wish community could test it on large apps to get feedback and improve if necessary.

6) it support @reach/router too, at the same time. people could use inside some part of a large app, and all will work with the same history.

7) sorry for late answer

Salvo

**Comment by julienben** [comment]
@salvoravida Now that you've explained a little more, it sounds like it could potentially be useful. Can you open a PR where you replace `connected-react-router` with `redux-first-history`? That way we can merge it into a local branch (not dev yet) and anyone who's interested can try it out as a first step.

@gretzky Any thoughts?

**Comment by gretzky** [comment]
My immediate reaction is that we need to be conscious of dependency fatigue -- aka adding dependencies into this repo that haven't been adopted / tested by other popular production boilerplates. Again, because our mission here is to stay production-ready, we need to make sure we uphold that meaning through the dependencies that we use and how we use them.
