### ISSUE TITLE
Preferred way to use convertion with immutable.js 

### ISSUE THREAD

**Issue by Absvep** [react-boilerplate/react-boilerplate#2469]
# React Boilerplate

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

Please direct redux-saga related questions to stack overflow:
http://stackoverflow.com/questions/tagged/redux-saga

For questions related to the boilerplate itself, you can also find answers on our gitter chat:
https://gitter.im/mxstbr/react-boilerplate

**Before opening a new issue, you may find an answer in already closed issues**:
https://github.com/react-boilerplate/react-boilerplate/issues?q=is%3Aissue+is%3Aclosed

## Issue Type

- [ ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md#bug-reports)
- [ x] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md#feature-requests)

## Description

I have a question on stack overflow about what is the preferred way to use immutable.js in react-boilerplate. I.e. where to use `toJS()` and `fromJS()`.

Please see my question on stack overflow, `https://stackoverflow.com/questions/53186890/correct-way-to-use-immutablejs-tojs-and-fromjs-with-redux`

**Comment by joshuaalpuerto** [comment]
Im my project. I ensure to use `fromJS` only on `reducer` `fromJS`. With `toJS` I rarely use this because this comes with a performance bottleneck. 

You can read more about it here:
https://redux.js.org/recipes/usingimmutablejs#immutable-js-best-practices

**Comment by Absvep** [comment]
@joshuaalpuerto Ok great, so you always convert data with `fromJS` in reducer? Like redux docs says:

`
// recommended
const newObj = { key: value }
const newState = state.setIn(['prop1'], fromJS(newObj))
// newObj is now an Immutable.JS Map
`

**Comment by joshuaalpuerto** [comment]
Yup

**Comment by Absvep** [comment]
@joshuaalpuerto Please see my update, I basically ask if you **always** convert in your reducer with `fromJS` ? Best Regards

**Comment by Absvep** [comment]
@joshuaalpuerto Thanks! Then I will follow same practice as well :)

**Comment by joshuaalpuerto** [comment]
Yeah thats' one thing I noticed. Im not pretty sure why they initialize their state with `fromJS` but  updating it with a regular object.

**Comment by Absvep** [comment]
@joshuaalpuerto I wonder that too...

**Comment by Absvep** [comment]
@joshuaalpuerto A simple answer could be that it is quicker. Else they would need to use immutable `get` or `set` etc their react components, yes?

**Comment by julienben** [comment]
(@gretzky - Just wanted to bring your attention to this if you haven't seen it. @Absvep makes an interesting point about the way we do Immutability in the sample app.)

Indeed the reducer doesn't convert the array of repos to an Immutable List.

I don't know why it was done that way but my guess would be one (or a combination) of the following reasons:

- It would mean having to do this ugly and confusing thing in the List component:

![image](https://user-images.githubusercontent.com/8948127/48672100-561a6100-eb3a-11e8-8260-33d7cc4a5397.png)

- Or to take the performance hit of `toJS` in the selector.

- Perhaps someone thought that `set` and `setIn` automatically convert the given data to an Immutable data type. That's how I understood Immutable at first (i.e. everything in the tree is Immutable).

I can't think of an elegant way to fix this.

- Either use Immutable all the way through but
	- components become confusing with a mix of POJO props and Immutable data
	- PropTypes become useless (unless you want to add immutable-prop-types).
- Or use `fromJS` and `toJS` in the reducers and selectors but get a big performance hit for... no benefit basically?

IMO this emphasizes the need to move away from Immutable ASAP. The downsides of its custom data types aren't worth the benefits of immutability, especially since there are now cleaner ways to do immutability.

**Comment by joshuaalpuerto** [comment]
@Absvep  @julienben Here's what I'm doing.

- No immutable when object is initialized inside the `container`
- Immutable  objects are only from the store.

> components become confusing with a mix of POJO props and Immutable data

I ensure that the containers only has the idea that the object is `immutable`. Component should only receive POJO, check the [HOC](https://redux.js.org/recipes/usingimmutablejs#use-a-higher-order-component-to-convert-your-smart-components-immutable-js-props-to-your-dumb-components-javascript-props) implementation here.

The component becomes easy to test because it doesn't have to be dependent with `ImmutableJS` 

> PropTypes become useless (unless you want to add immutable-prop-types).

This is correct for `Containers` but for `Component` it should be just `Object` or `Array` since it's just POJO.

> IMO this emphasizes the need to move away from Immutable ASAP.

I strongly agree with this. Because you have to learn `immutablejs` to manipulate the `array` or `object` to ensure you don't use `toJS` often. Which is an **overhead**.

**Comment by julienben** [comment]
My personal preference is to switch to `immer`. You can see what that would look like in PR #2380.

**Comment by Absvep** [comment]
@julienben Thanks. I will do that to with the help of your PR :)
