### ISSUE TITLE
Something has changed over night... 

### ISSUE THREAD

**Issue by michaelcuneo** [react-boilerplate/react-boilerplate#2506]
Yesterday I was working on a brand new clone of React-Boilerplate with an idea... came in to work today to continue, and pulled it to this computer here... somehow between yesterday and today, there is an update to something that has killed the entire project on all of my machines, which are all running different environments. Mac/Ubuntu/Windows.

Uncaught Error: You may not call store.getState() while the reducer is executing. The reducer has already received the state as an argument. Pass it down from the top reducer instead of reading it from the store.
    at Object.getState (redux.js?a67e:112)
 
This error occurs with a fresh clone of RB on all of my machines, irrespective of React version. Not sure what's causing it yet, but as soon as I find the issue, I'll let you know. If anyone else has any ideas... 

Somehow related to the LanguageProvider Connector?

**Comment by michaelcuneo** [comment]
Oh... the original machine that was working fine last night is also affected. Just thought I'd add that incase the original post suggested that I'd actually changed something... 

The error occurs from a fresh install. i.e.

git clone https://github.com/react-boilerplate/react-boilerplate.git
cd react-boilerplate
npm run setup
npm run start

Absolutely no changes... Error across multiple environments/machines.

**Comment by denisinla** [comment]
Just cloned fresh, ran setup and started up and didn't receive any errors. Is your terminal returning anything?

**Comment by michaelcuneo** [comment]
Nothing in the terminal. All errors from console.

![screen shot 2018-11-30 at 3 17 05 pm](https://user-images.githubusercontent.com/12700009/49268372-3af10f00-f4b3-11e8-9104-21b34b149c8f.png)

**Comment by michaelcuneo** [comment]
Wow, o.k. I've narrowed it down. It's Chrome. The error does not appear in Firefox or Safari.

**Comment by gretzky** [comment]
Sorry but I'm actually begging you to please fill out the issue template in the future. Please. Seriously. It's there for a reason. I'm calling you out specifically because [you](https://github.com/react-boilerplate/react-boilerplate/issues/2506) [never](https://github.com/react-boilerplate/react-boilerplate/issues/2416) [have](https://github.com/react-boilerplate/react-boilerplate/issues/2389) [done](https://github.com/react-boilerplate/react-boilerplate/issues/2295) [it](https://github.com/react-boilerplate/react-boilerplate/issues/1419).

I don't mean to come off rude (and I'm aware it probably does come off rude), but the maintainers of this project wrote and implemented those issue templates so it can help us help you. We spend our time maintaining this for free- that includes answering issues. Please do not delete the issue template because you feel it doesn't apply to you. It's for the maintainers.

**Comment by michaelcuneo** [comment]
I always fill out a bug report if the relevance and time constraints permit, I develop over too many projects to sometimes warrant the irrelevant questioning. i.e.

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
Clear Description is in my first paragraph

## Steps to reproduce
Steps to reproduce is in my first paragraph

(Add link to a demo on https://jsfiddle.net or similar if possible)
Demo is irrelevant because it cannot be reproduced over my vast live environments.

**Expected behavior**
This question has always been stupid in most cases... the expected behavior is for it to not be broken.

**Screenshots**
Not applicable, the error in the connectedRouter component is a common error that can easily be explained in a word or two. I don't really need screenshots to explain this, but did for further reference.

## Versions

- React-Boilerplate: Latest
- Node/NPM: Too many different versions across toi many different environments.
- Browser: Too many different versions across toi many different environments.

This took me about 5 minutes longer than writing it out simply in a few paragraphs, because I had to wrap my head around decisions about relevance, how the questions directly relate to my issue, and deciding how to ask the question in this point format to suit however you guys will read it.

All of my other questions have been general questions...

#1419 . How is that a bug? You never had 'Feature Request' when I wrote it.
#2295 This actually filled in using your template! The old one. Why? Because it was 100% relevant to use the bug system in this instance.
#2389 Again, Feature Requests didn't exist as a template on this project when I wrote this.
#2416 Another general question.,.. one liner. Not even a hard one.

I know you have a #Slack I think, or a Gitter... can't remember which but not one single person answers a single question on there, except me.

**Comment by gretzky** [comment]
I'm sorry that you think pieces of the template are stupid, but again, that issue template is for the maintainers so that they can help you. I understand more keystrokes = more time wasted, but imagine the amount of keystrokes that the maintainers do for free to help users with issues, etc.

If you don't want to do the absolute bare minimum for the maintainers of open source repositories who dedicate their free time and free energy so that you can use this boilerplate for free and get free help, then that's on you. Just know that I will do the bare minimum for you, which is hit the 'close' button.

**Comment by julienben** [comment]
For someone who wants to save keystrokes, your issue description contains irrelevant backstory and the title is no better. Please use the templates or don't bother posting.
