### ISSUE TITLE
Calling an action on componentDidMount is not intercepted by saga

### ISSUE THREAD

**Issue by christianbobaila** [react-boilerplate/react-boilerplate#2551]
I am working on a project using the boilerplate and I encountered the following issue:
- when I am trying to call an action in componentDidMount, the related saga does not catch it so it does not have any effect.

If I am wrapping the action inside a setTimeout method and calling it with a 500ms delay, it works.

index.js
`const mapStateToProps = createStructuredSelector({
  billingPage: makeSelectBillingPage()
});

function mapDispatchToProps(dispatch) {
  return {
    getBillingInformation: () => dispatch(getBillingInformation())
  };
}

const withConnect = connect(
  mapStateToProps,
  mapDispatchToProps
);

const withReducer = injectReducer({ key: "billingPage", reducer });
const withSaga = injectSaga({ key: "billingPage", saga });

export default compose(
  withReducer,
  withSaga,
  withConnect
)(BillingPage);`

actions.js
`import { 
  GET_BILLING_INFORMATION, 
  GET_BILLING_INFORMATION_SUCCESS, 
  GET_BILLING_INFORMATION_ERROR } 
  from './constants';

export function getBillingInformation() {
  return {
    type: GET_BILLING_INFORMATION
  };
};`

saga.js
`export function* getBillingInformation() {
  try {
    yield put(getBillingInformationSuccess({ payload: {} }));
  } catch (err) {
    yield put(getBillingInformationError({ payload: err }));
  }
}

export default function* billingSaga() {
  yield takeLatest(GET_BILLING_INFORMATION, getBillingInformation);
}
`

Do you have any idea on how I could solve this issue?

**Comment by gretzky** [comment]
Sorry, we try to keep this channel open for issues with the boilerplate itself rather than specific-project help. Please post your question to StackOverflow. Make sure you're formatting your code as well.

**Comment by julienben** [comment]
The saga should already be available in componentDidMount...

**Comment by christianbobaila** [comment]
Hi @julienben,
Thanks for the response. Unfortunately that was the behaviour I was expecting and it seems that it is not happening. Could you please give me support regarding this issue?

**Comment by julienben** [comment]
Your code looks fine so the issue is probably elsewhere.

- Did you make any changes to the internals of the boilerplate? The store setup? The saga and reducer injection mechanisms?
- Did you upgrade dependencies without checking if they had breaking changes?

If you answered no to both, the only way we can help you is if you provide a sample repository where this issue can be reproduced. Can you do that?

If not, there's nothing else we can do for you. It's important to understand that none of us do this for money. It's just volunteering on top of our regular jobs. So if you need help you need to make it easy for us to help you.
