### ISSUE TITLE
v3.7.0 was a mistake

### ISSUE THREAD

**Issue by joshuambg** [react-boilerplate/react-boilerplate#2577]
**Is your feature request related to a problem? Please describe.**
The largest difference between 3.6 and 3.7 is the DLL setup was removed. The reasons for this change are mistaken. The DLL setup exists primarily to speed up bundling while in development. This entire setup was replaced with optimizations that only exist in the webpack production config. Very large projects will suffer from this change.

https://github.com/react-boilerplate/react-boilerplate/commit/f3a3b2113545d32b2fc05c89c1169be50214d163#diff-189d419c3ddeb1ab35d04d85d068e7a9

**Comment by julienben** [comment]
IMO this was a positive change.

I have a few large projects built with RBP and my dev environments didn't slow down in any way after removing the DLL boilerplate. On the other hand, I'm no longer bored out of my mind while I wait for the DLL to be generated.

If it does make a big difference to you, you can add it back in using the code from the relevant PR. It won't be back in the next version of RBP though.

**Comment by gretzky** [comment]
I agree that the DLL setup has been outgrown, there are several other ways you can optimize now with webpack and other, smaller dependencies or scripts. I've had the same experience as @julienben with large projects not being affected.

**Comment by joshuambg** [comment]
@julienben @gretzky Examples or you're wrong.

**Comment by julienben** [comment]
Examples?

**Comment by csantiago132** [comment]
@josuambg just because someone does things differently, doesn’t mean that person is wrong, also, demanding things in a negative, not-so-nice way will not take you far. This boilerplate is one of the best out there and both Julien and Gretzky are trying to help, giving up their free time to do so. I hope you can solve your issue with the boilerplate!

**Comment by gretzky** [comment]
@joshuambg There are several ways to talk about this, don't choose the way that could potentially [violate the code of conduct](https://github.com/react-boilerplate/react-boilerplate/blob/master/CODE_OF_CONDUCT.md).

If you need examples, you can look up literally any other React project that exists. Nobody else uses the DLL setup, it wasn't adopted by any other larger project because there are other ways. The DLL setup was used early on before tooling could handle it, and it was super useful then and we can still draw that use from it. You're more than welcome to cherry-pick it from previous rbp versions into your project.

**Comment by joshuambg** [comment]
Guess you're wrong.

**Comment by gretzky** [comment]
Nah, you're just rude. Your way is not the 'right' way.
