### ISSUE TITLE
Not able to open more than six tabs in the same window.

### ISSUE THREAD

**Issue by amitpareek49** [react-boilerplate/react-boilerplate#2653]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
Not able to open more than six tabs on the same browser window.

## Steps to reproduce
Run the react boilerplate code using npm start. Try accessing the application (http://localhost:3000) on more than six tabs. The first six tab are launched properly, but the seventh tab does not load at all. If any of the remaining six tabs is closed the seventh window is launched successfully.

(Add link to a demo on https://jsfiddle.net or similar if possible)

**Expected behavior**
Any number of tabs should open on sending the request from the browser.

**Screenshots**

## Versions

- React-Boilerplate: 4.0.0
- Node/NPM:v10.15.3 /6.4.1
- Browser:Chrome (69.0.3497.100) and other browsers.

**Comment by julienben** [comment]
This is due to Chrome not being able to open more than 6 connections per host.

I'm not sure it's something that can be configured. 

Check this out for more info: https://docs.pushtechnology.com/cloud/latest/manual/html/designguide/solution/support/connection_limitations.html

Will close this issue as it's not something that can be fixed inside the boilerplate.

Good luck!
