### ISSUE TITLE
How to generate class based container ?

### ISSUE THREAD

**Issue by imtechieraj** [react-boilerplate/react-boilerplate#2655]

**Comment by thisisrajkumar** [comment]
Thank you for your clarification. Okay Let's I explain the issue in briefly. 
Initially I started this boilerplate (Version is 3.7.0). If I create one container that time It will ask three different type

**Comment by imtechieraj** [comment]
Thank you for your clarification. 

Okay Let me explain the issue briefly.

Initially I started this boilerplate with version **@3.7.0**. When I created one container, it shows three different types of container listed below

                       **Stateless function, 
                       React.PureComponent , 
                       React.Component** .  

**Screenshot1:** 
[
![Capture](https://user-images.githubusercontent.com/35949605/57828559-84b38480-77c9-11e9-8a08-a63a2e237944.PNG)
](url)

Currently I started a new project with updated version  (**@4.4.0**) . But those three containers dint get displayed.

**Screenshot2 :**
[
![Capture 2](https://user-images.githubusercontent.com/35949605/57828938-e6282300-77ca-11e9-9e87-076e825ab6ea.PNG)
](url)

I wanted to get it created as Class based container.As of now,it is not getting created like that.  

**Screenshot3:**

![Capture 3](https://user-images.githubusercontent.com/35949605/57829041-4ae37d80-77cb-11e9-91a7-c47f489ae823.PNG)

It will be great if you reply for my query.

Question: **What I need to do to get those 3 options in CLI?**

**Comment by julienben** [comment]
Hey @thisisrajkumar,

We recently released v4 and removed class-based containers from the generators. We did this because we want to keep up to date with the best practices in React and, since Hooks came out, functional components (vs classes) have become the recommended way of writing with React. 

The PureComponent vs Component choice was replaced with an option to wrap your component inside React.memo.

You can read more about it [here](https://github.com/react-boilerplate/react-boilerplate/releases/tag/v4.0.0).

If you still want classes, you have two choices: Use v3.7 or rewrite the generators in v4 for your own needs.
