### ISSUE TITLE
suggestion about crud generator

### ISSUE THREAD

**Issue by NikolaMandic** [react-boilerplate/react-boilerplate#2659]
**Is your feature request related to a problem? Please describe.**
I'd like generators for repetitive tasks like for crud resource. or action

**Describe the solution you'd like**
here is one https://github.com/tymbac/react-boilerplate

**Describe alternatives you've considered**
creating this manually

**Additional context**
no

**Comment by vineyardbovines** [comment]
Not enough detail. Closing.

**Comment by NikolaMandic** [comment]
@gretzky what about this

https://github.com/tymbac/react-boilerplate/commit/670513384da23afe834407f958b9f175253b0b3d

**Comment by julienben** [comment]
Agreed with @gretzky.

This isn't an irrelevant issue though. We do write a lot of boilerplate code for new actions. It's repetitive and time-consuming.

I don't think a CRUD actions generator is the right solution though because it's extremely specific. Personally I would have 0 use for CRUD actions and I suspect that's the case for most users of rbp.

I wanted at some point to add a generic action generator but couldn't figure out a few aspects of it. If you want to give that a shot, you're more than welcome.

Another solution is to switch to/add one of those redux helper libraries that takes care of a lot of this work for you. You're also more than welcome to propose that as a change that we can discuss and eventually prepare a PR.

**Comment by NikolaMandic** [comment]
@julienben  hm I actually wrote action generator too but I seemed to have been inept at formulating issue properly. I thought of elaborating more latter just wanted to find out sentiment of people here if they would like something similar.

main thinking behind this is since after few of projects it looks to me that its highly likely that in next one a need for crud action will appear
if not for more resources then at least for one 

so having to copy paste these things from one place to another does not seem that attractive I wanted to hear do other people had similar issues
