### ISSUE TITLE
Move reducer/saga injection to separate library

### ISSUE THREAD

**Issue by BenLorantfy** [react-boilerplate/react-boilerplate#2698]
**Is your feature request related to a problem? Please describe.**
I use this boilerplate for multiple projects, which means I have some duplicate code in my utils folders for the reducer/saga injection.

**Describe the solution you'd like**
It would be nice to move the reducer/saga injection to a separate library, that this boilerplate then imports as a dependency. This would reduce code duplication when using this boilerplate for multiple projects. It would also let developers use the reducer/saga injection without using the entire boilerplate.

**Describe alternatives you've considered**
N/A

**Additional context**
I'd like to work on this if I can get the blessing of the maintainers. I'd probably also need help from the maintainers in creating a separate repo within the react-boilerplate organization. Alternatively, we could set up a monorepo, but that would be more work.

**Comment by BenLorantfy** [comment]
@julienben Any thoughts on this?

**Comment by julienben** [comment]
Sounds like a good idea in theory.

A few thoughts:
1. I'm assuming we're talking about the code in these files: [injectReducer](https://github.com/react-boilerplate/react-boilerplate/blob/master/app/utils/injectReducer.js), [injectSaga](https://github.com/react-boilerplate/react-boilerplate/blob/master/app/utils/injectSaga.js), [reducerInjectors](https://github.com/react-boilerplate/react-boilerplate/blob/master/app/utils/reducerInjectors.js), [sagaInjectors](https://github.com/react-boilerplate/react-boilerplate/blob/master/app/utils/sagaInjectors.js) + the corresponding tests. Is that correct?
2. This code is very specific to react-boilerplate. It expects a Redux store as configured inside [configureStore](https://github.com/react-boilerplate/react-boilerplate/blob/master/app/configureStore.js) and as verified by [checkStore](https://github.com/react-boilerplate/react-boilerplate/blob/master/app/utils/checkStore.js). How do we deal with the tight coupling between these? (At the very very least, I think the name of the project should be specific, i.e. react-boilerplate-injectors, and the documentation should be detailed.)
3. Whenever the idea to turn react-boilerplate into a monorepo has arisen, we've tried to stay away from it because many devs come to this repo to learn best practices and a monorepo would feel over-engineered and harder to grok. It could make sense as an additional package in the react-boilerplate organization though.
4. Not that this code would require a ton of maintenance but nonetheless, would you be willing to take care of it? At this time react-boilerplate itself doesn't have many maintainers/contributors and I wouldn't want to add additional projects which might fall into disrepair.

Btw, in my team at work, we build 10+ frontend apps from the same react-boilerplate-inspired monorepo. It's not a Lerna monorepo though. It just has an `apps` folder (note the "s") containing multiple apps and we use env variables to start/build/deploy the relevant app. It allows us to share much more than just the injectors (i.e. all the config files, the generators, shared components, etc). I'd be happy to help you understand how that works because IMO it would be a more holistic solution to your issue.

**Comment by BenLorantfy** [comment]
Thanks for the detailed response. Here’s my answers to the above points:

1. Yep
2. I think we could pull some code out of configureStore and checkStore and move it to the library. For example, we could create a ‘setupInjectors’ function and a ‘checkInjectorsSetup’ function and export these from the new library. Then ‘configureStore’ and ‘checkStore’ could respectively use these two functions.  I think this would reduce the implicit coupling. And then of course all that would need to be documented. If we do that I’m not sure the library needs react-boilerplate in the name, since it could be used without the boilerplate.
3. Good point, I agree.
4. Yep. I’ve been looking for a bigger open source project besides just small bug fixes and typing fixes so I’m willing to maintain this for the foreseeable future.

Regarding your side note, that seems like a good approach, but would require bigger changes our side that I don’t think we have time to make right now. I’d also argue a library has the added bonus of being easier to upgrade and keep up to date with the upstream.

**Comment by julienben** [comment]
I'd like to hear back from other contributors here but my hunch is that we might prefer to leave the injector code in the main rbp repo.

Mostly for these reasons (from my POV at least):

1. Pulling code from `configureStore` and `checkStore` feels like it would still make it hard to tell where the injectors end and where the boilerplate begins.

2. It would still feel a little over-engineered and thus make it hard for people who just come to learn from the rbp setup and code.

It wouldn't in any way stop you from having a copy of the injectors living in a separate library.

This code changes rarely enough that I don't think there'd be too much of an issue with keeping rbp and the injectors library in sync.

Do you know precisely what the API would look like? Which functions would you expose and what would be their inputs and outputs?

My suggestion would be to just go ahead and build this library, possibly inside the react-boilerplate organization.

When it's ready, you can start using it for your own projects and we can also reconsider at that time whether or not we'd want react-boilerplate itself to use it.

**Comment by vineyardbovines** [comment]
I agree that I'd like to see the API design but I also recognize sometimes it's easier to just start writing the library in order to flesh out the design itself 😄.

I'm not a great reliance here- I don't use sagas in any of my projects, never really have with the exception of working with this bp BUT I will say one point @julienben made that I also want to echo is keeping this bp simple so that newcomers can get acquainted with a typical, production-ready react app.

**Comment by BenLorantfy** [comment]
I went ahead and created the basics of the library so we can see what it would look like.

Here's the rough api design: https://github.com/BenLorantfy/react-redux-injectors#api-reference
Here's a link to the changes that would be required to the boilerplate: https://github.com/react-boilerplate/react-boilerplate/compare/master...BenLorantfy:master

A few notes:
1. I ended up moving `checkStore` to the library. I think it makes sense here because it seems like it's purpose is to ensure the store is setup properly for the injectors. It's also not used outside of the injectors. We may not even want to export this function, since it's just used internally at the moment.
2. You can see how to setup the injectors here: https://github.com/react-boilerplate/react-boilerplate/compare/master...BenLorantfy:master#diff-ea94aca90fbef7f544d2a96cf1da5f8eR50 .You just call `setupStoreForInjectors` with the store and a few options required for the setup. 
3. You can see how the imports would have to change here: https://github.com/react-boilerplate/react-boilerplate/compare/master...BenLorantfy:master#diff-b40dc3de2b66cf46597584200a5599f7R15 (We may want to write a codemod to help with this)
4. These lines wouldn't be needed. I just had to add them to get the linking to work properly for local development. https://github.com/react-boilerplate/react-boilerplate/compare/master...BenLorantfy:master#diff-0ce70994be1370e72714431f8e7cc804R122
5. After implementing this, I think it actually makes the boilerplate simpler. It hides away the complexity of the injectors, and allows us to remove a lot of code from the boilerplate. 
6. I also think the injector setup in the `createStore` function is clearer / more expressive now.
7. I was able to remove a somewhat backwards coupling. A file in the utils depended on the reducers file. This was replaced by attaching a `createReducer` property to the store, similar to the `runSaga` function on the store. See here for the old import: https://github.com/react-boilerplate/react-boilerplate/compare/master...BenLorantfy:master#diff-85e83bd213032a5aa4c82d09f55994d9L5
8. The documentation isn't complete. For example, I still have to document the hooks.
9. I'd still like to make a few changes to the library. For example, I'd like to try to remove the dependency on lodash, since lodash is very big and we're only using a few methods that we could replace easily. ~I'd also like to add a typescript `index.d.ts` file~ (done). Plus a few other things still need to be setup including linting, CI, etc.

@julienben @gretzky Please let me know what you think of the api design and boilerplate changes.

**Comment by julienben** [comment]
(Sorry, super busy rn. I know this is waiting for review. Will get to it asap.)

**Comment by vineyardbovines** [comment]
I like the idea of this being separate I think after seeing this implementation. I don't think I could be convinced of rbp becoming a monorepo, but I can see the validity in having some of this logic totally external. 

The only thing I'd say before we bring it in fully would be to make sure the docs are where they need to be / match the rest of our docs. I'll leave the saga investigation to @julienben.

**Comment by BenLorantfy** [comment]
Yeah I don't think a monorepo makes sense, I was just mentioning it as an option. I think the better option would be a separate repo which could be under the react-boilerplate organization.

**Comment by bwhitty** [comment]
@BenLorantfy I'm actually pretty interested in this. I've taken a lot of inspiration from react-boilerplate's "modular redux" implementation, and would like to help get it extracted.

I've also seen https://github.com/Microsoft/redux-dynamic-modules but think it's a bit much

**Comment by vineyardbovines** [comment]
@BenLorantfy sorry for my lack of further response-- I'm getting married next week, I've never been so busy with planning!

**Comment by BenLorantfy** [comment]
@gretzky Haha no problem, that's a little more important than a GitHub issue.

I'm mostly waiting for @julienben 's response anyway... nudge nudge, wink wink 😉

**Comment by BenLorantfy** [comment]
@bwhitty That library is interesting, I didn't know that existed. It's similar to the injection in rbp but the api is a little different.

**Comment by BenLorantfy** [comment]
@julienben Not trying to be an annoyance but have you gotten a chance to look at this yet?

**Comment by julienben** [comment]
Hey @BenLorantfy,

Sorry for how long it took me to reach this... I only have so much time I can dedicate to rbp + I was on holiday for a while.

Overall, this LGTM. I'd be happy to help you open a new project in the react-boilerplate org and get this working.

Before that, do you have a final name?

My vote still goes to `react-boilerplate-injectors` or `rbp-injectors` because when you also think of the `redux-sagas` setup it's just so specific to `react-boilerplate`.

If you want to stick to `react-redux-injectors`, you might still want to add `sagas` to the name though since this is still specific to `redux-sagas` and might not be obvious right away. (Or at the very least make sure it's mentioned early on in the README.)

Some other thoughts:
- Your documentation should start with an explanation of what this project is about. Before publishing we'll look in more details at making sure the 2 projects are aligned.
- You need to set up your repo so that your `npm` build contains a `dist` folder from which users can import. (Check out [bili](https://github.com/egoist/bili). `immer` and many others use that.)
- Your `react-boilerplate` branch should use `dev` as its base branch. It also needs to update the template app as well as the generators.
- In your `package.json`, could you pin the dependencies the same way it's done inside `react-boilerplate`?
- Question: Why expose the `checkStore` API to the user? Isn't it something that's only useful inside the injector functions?
- Regarding the `lodash` dependency you shouldn't have to worry about it. There are several ways to guarantee that you're only importing the parts you need (as done by `react-boilerplate` following [this article](https://nolanlawson.com/2018/03/20/smaller-lodash-bundles-with-webpack-and-babel/)).

I'm sure more stuff will come up and it'd also be great if we can get others to review closer to publication. For now though let's pick a name and open the project so you can set up Travis and continue working from there.

**Comment by BenLorantfy** [comment]
@julienben No worries, hope you enjoyed your holiday. That all sounds great; I'm excited to get started. 

Regarding the name: I'm hesitant to add rbp to the name because I think we can make it de-coupled enough to be used outside of rbp if users want to. 

I do see your point about adding `saga` to the name though. This is the best name I can think of at the moment: `reducer-saga-injectors`. We could always rename up until the point we publish to npm.

I agree with all your other points, I'll make sure to address them as I work on this. If you could help me setup a repo that would be great. Thinking we create an empty repo and I'll do a PR into it with what I have so far?

**Comment by julienben** [comment]
You should have an invitation to https://github.com/react-boilerplate/injectors in your email.

I simply called it `injectors` for now since we can rename it later. It's more or less set up like `react-boilerplate`.

Let's please follow the same git strategy:
- Never push to `dev` or `master`
- Branch from `dev` to write your code
- Merge it into `dev` when ready
- Merge `dev` into `master` when releasing a new version
- Squash merging only for super clean history

**Comment by justingreenberg** [comment]
awesome idea, very excited for this!

re: the [setupStoreForInjectors](https://github.com/BenLorantfy/react-redux-injectors/blob/master/src/setupStoreForInjectors.js) function, i would consider exporting a [store enhancer](https://redux.js.org/glossary#store-enhancer) since it's safer than monkey patching and is really the canonical approach to extending the store API...

```ts
type StoreEnhancer = (next: StoreCreator) => StoreCreator
```

so, something like...

```js
export default function setupStoreForInjectors(options) {
  invariant(
    conformsTo(options, {
      runSaga: isFunction,
      createReducer: isFunction
    }),
    '(injectors...) setupStoreForInjectors: options `runSaga` and ' +
      '`createReducer` are required.',
  )
  return createStore => (...args) => {
    const store = createStore(...args)

    return {
      ...store,
      createReducer: options.createReducer,
      runSaga: options.runSaga,
      injectedReducers: {}, // Reducer registry
      injectedSagas: {}, // Saga registry
    }
  }
}
```

which would make the example usage:

```js
import { createStore } from "redux"
import { setupStoreForInjectors } from "react-redux-injectors"

function createReducer(injectedReducers = {}) {
  const rootReducer = combineReducers({
    ...injectedReducers,
    // other non-injected reducers can go here...
  });

  return rootReducer
}

const runSaga = sagaMiddleware.run

const store = createStore(
  createReducer(),
  undefined,
  setupStoreForInjectors({ 
    createReducer,
    runSaga,
  })
)
```

**Comment by BenLorantfy** [comment]
@justingreenberg Seems like a good idea, I'll try it out

**Comment by BenLorantfy** [comment]
@julienben Sounds good, thanks

**Comment by BenLorantfy** [comment]
OK, first PR is up for review to the new library 😁: https://github.com/react-boilerplate/injectors/pull/1

**Comment by kaiwa** [comment]
Awesome, that's what I was trying to do in my project recently. I copied the injection stuff from react-boilerplate into a create react app skeleton a while ago and now was working on improving the project's structure and extracting the injection functionality into a separate package. In future I might be able to just use your package instead :+1:

**Comment by BenLorantfy** [comment]
Tooling and docs PR is up: https://github.com/react-boilerplate/injectors/pull/2 

By the way, I think we need a little bit more discussion to decide on a name. These are a few options:

| name                        | pros                                                                | cons                                                                                                                                                                                                           |
|-----------------------------|---------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `redux-injectors`             |  Concise; Shorter to type; Conveys it's for use with redux       |  Does not convey support for redux-saga; Does not convey it's for use with react.                                                                                                                          |
| `reducer-saga-injectors`      |  Conveys support for redux-saga; Conveys support for redux        |  Awkward to say; Longer to type                                                                                                                                                                              |
| `react-boilerplate-injectors` |  Conveys usage by react-boilerplate                                |  Does not convey support for redux; Does not convey support for redux-saga; Couples name to react-boilerplate; i.e. name does not make sense if using library outside of react-boilerplate; Longer to type |
| `react-redux-injectors`       |  Conveys it's for use with react; Conveys it's for use with redux |  Does not convey it's for use with redux-saga; Longer to type                                                                                                                                                |
| `dynamic-redux`               |  Concise; Shorter to type; Conveys it's for use with redux       |  Does not convey support for redux-saga; Does not convey for use with react                                                                                                                                  |

I'm leaning towards `redux-injectors` because I think it's a decent balance between brevity when typing import statements and expressiveness.

**Comment by bwhitty** [comment]
If I were to throw in my 2c, I'd say `dynamic-redux` captures the ethos the best. Fundamentally, the package is about running Redux in a way that allows it to become "dynamic" at runtime. It's also general enough to cover the fact that the package deals with React and Redux Saga.

The reason I'd lean towards that name instead of `redux-injectors` is that the "injectors" part to me feels tied to the current API (which has functions called `inject`, etc), and it doesn't convey the inverse of injecting, which is removing the reducers / sagas upon component unmount. I think "dynamic" conveys that a bit more.

Negatives to `dynamic-redux` is that there are a couple packages in the NPM ecosystem which already carry a name like it (including Microsoft's https://github.com/Microsoft/redux-dynamic-modules): https://www.npmjs.com/search?q=dynamic%20redux while `redux-injectors` simply has less: https://www.npmjs.com/package/redux-inject-reducer-and-saga

Interestingly, it also appears someone has already shipped something which tries to extract react-boilerplate's reducer/saga injection like what is being done here 😄 https://www.npmjs.com/package/redux-inject-reducer-and-saga (though it appears more opinionated, and is tied to Immutablejs, etc)

**Comment by BenLorantfy** [comment]
Good points. I'm also OK with `dynamic-redux`

**Comment by julienben** [comment]
Interesting points about `dynamic-redux`! It feels like a more "ambitious" name which could even expand the scope of the project.

Perhaps as a start the documentation can "zoom out" from just explaining injection and instead explain from a larger POV what it enables in a React+Redux app (=> runtime management of reducers and sagas).

And maybe down the road, it could *somehow* be rewritten to disconnect from sagas and instead work generically with similar redux middleware.

(I'm also fine with `redux-injectors` btw.)

**Comment by vineyardbovines** [comment]
I personally don't like ambiguous names like `dynamic-redux`, it tells me nothing other than it's probably used with redux. I prefer the long, wordy ones-- `redux-saga-injectors`, `redux-injectors`, etc. especially when the project is scoped to very specific libraries, like we are here. `react-redux-saga-injectors` is too long, but I'd still prefer something more wordy along those lines. That's just me!

**Comment by BenLorantfy** [comment]
Fair points. I think I'm good with either `redux-injectors` or `dynamic-redux`. `dynamic-redux` does feel less coupled to the API.

**Comment by julienben** [comment]
Ok so we can eliminate `react-redux-saga-injectors` for the reasons cited above but also `redux-saga-injectors` because it just sounds related to sagas but not reducers as well.

That leaves us with `react-redux-injectors`, `redux-injectors` and `dynamic-redux`. My vote goes for keeping only the first two options. They feel like more of a middle ground between the "benefits" of `dynamic-redux` and the "descriptiveness" of the longer options.

As for which to settle on... I have no strong preference. 😅

**Comment by julienben** [comment]
A great benefit that will come out of this project: Because `react-boilerplate` isn't a dependency we don't have any usage stats. But all future `react-boilerplate`-based projects will have this library so it'll give us some kind of usage stats. (Obviously we'll also have non-`react-boilerplate` users of this library but it'll be interesting nonetheless.)

**Comment by jwinn** [comment]
> Ok so we can eliminate `react-redux-saga-injectors` for the reasons cited above but also `redux-saga-injectors` because it just sounds related to sagas but not reducers as well.
> ..._[omitted]_

Just my $0.02 on the matter, but I feel `redux-saga-injectors` best encapsulates what the project provides, as sagas are a part of this (and reducers are inherently a part of redux). But I'm not that partial 😉 

Anyway, good work on all of this @BenLorantfy (and @julienben et al)

**Comment by BenLorantfy** [comment]
I kind of want to avoid `redux-saga-injectors` because I can foresee in the future adopting a "plugin" type system so people could use the library without redux-saga, and then use a plugin if they want sagas. This could enable the library to be used with other side-effect libraries as-well.

**Comment by julienben** [comment]
I agree with @BenLorantfy. Let's not attach this to sagas permanently.

Btw, I wanted to release react-boilerplate v4.1 with the release of styled-components v5 but it's been stuck on beta 8 since July 1st so IMO the new goal should be to finish this project, embed it into react-boilerplate and release. (The release of rbp 4.1 can also be a small opportunity to promote the injectors.)

**Comment by jwinn** [comment]
@BenLorantfy valid (and good) point, then `redux-injectors`, if available, makes sense 😄

@julienben sounds like a good plan 👍

**Comment by BenLorantfy** [comment]
ok, for the sake of making a decision, do we go with `redux-injectors` ?

**Comment by julienben** [comment]
Sounds good to me.

**Comment by BenLorantfy** [comment]
OK, I think these are the last few things to do:
- [x] Review and merge this PR: https://github.com/react-boilerplate/injectors/pull/3
- [x] Rename repo within GitHub settings (Need help with this one)
- [x] Merge dev to master (I think we might want to not squash commit (i.e. use a merge commit) this so we maintain the history)
- [x] Create GitHub release ([done](https://github.com/react-boilerplate/redux-injectors/releases/tag/v1.0.0))
- [ ] Publish (Need help with this one)
- [ ] Make PR to change rbp to use redux-injectors

**Comment by BenLorantfy** [comment]
We're almost there! @julienben I'm assuming you want to do the actual publish to npm. After that, I can update [my PR](https://github.com/react-boilerplate/react-boilerplate/pull/2749) to use the published version :)

**Comment by julienben** [comment]
We should publish to npm as an organization so it's not tied to either one of us but `react-boilerplate` seems to be taken already :(

There's [this page](https://www.npmjs.com/org/react-boilerplate?tab=packages) and also it told me this when I tried to create it:

![image](https://user-images.githubusercontent.com/8948127/65435741-abde2a80-de29-11e9-85f3-1c19ac7fc8b1.png)

Doesn't seem like there's an easy way to find out who it belongs to. I'll write to @mxstbr on Twitter to see if he knows. Otherwise, we might need to find an alternative name.

**Comment by julienben** [comment]
(I wrote to npm support as well. Will update if I get a reply.)

**Comment by julienben** [comment]
npm won't give us contact info for the owner of the react-boilerplate organization (makes sense) but they've offered to contact the current owner on our behalf and ask if they would be willing to transfer ownership. They say it can take up to 4 weeks though (to give them time to respond) so let's wait a little and if we don't get a response within a week or two we can start considering alternative names.

**Comment by julienben** [comment]
(If we're impatient, we can also consider publishing under a different org name - redux-injectors? - and transfer ownership of the package if/when we get ownership of react-boilerplate.)

**Comment by BenLorantfy** [comment]
@julienben I would probably prefer the second option of transferring the package but that's just me 😄

**Comment by julienben** [comment]
"The owner of the react-boilerplate organization account has responded back and has declined to release ownership of the scope." 😓

Doesn't seem very fair since it's not even used but there's nothing we can do about it. The important thing is that `redux-injectors` still seems available.

I ended up creating an organization called `reactboilerplate` and invited you. Feel free to publish ;)

**Comment by vineyardbovines** [comment]
Some people just be like that! Hopefully this won't create too much confusion in the future.

**Comment by BenLorantfy** [comment]
@julienben So I had a few hick-ups while publishing. 

1. I tried following [these docs](https://docs.npmjs.com/configuring-your-npm-client-with-your-org-settings#changing-default-package-visibility-to-public) to publish under the reactboilerplate org, but it just published under my user account 🤷‍♂ . I invited you as a maintainer, so you should be able to [transfer it to the org](https://docs.npmjs.com/managing-team-access-to-org-packages#adding-package-access-to-a-team-on-the-web). I tried but I don't think I have access since I'm not the org owner.

2. I accidentally published 1.1.0 on dev instead of 1.0.0 on master. I hastily unpublished 1.1.0 and published 1.0.0, but now the 1.1.0 version [can't be republished](https://docs.npmjs.com/cli/unpublish) 🙁 
> Even if a package version is unpublished, that specific name and version combination can never be reused. In order to publish the package again, a new version number must be used. 

Therefore, I made [this PR](https://github.com/react-boilerplate/redux-injectors/pull/6) to bump the version. Once that is merged, we can merge dev -> master again and publish the changes you made to the hooks as v1.2.0. 

Apologies for any inconvenience.

**Comment by BenLorantfy** [comment]
Last PR is ready for review now https://github.com/react-boilerplate/react-boilerplate/pull/2749 🙂

**Comment by julienben** [comment]
Closing this as we're about to merge #2749. 🎉
