### ISSUE TITLE
Many reported vulnerabilities.

### ISSUE THREAD

**Issue by aristretto** [react-boilerplate/react-boilerplate#2705]

**Comment by aristretto** [comment]
I don't really have bandwidth to fix this, and a quick (and I do mean quick) search through issues didn't surface anything that looked like a dupe of this. Please feel free to close if this is known / reported / no one cares (lol).

**Comment by julienben** [comment]
Why did you delete before we had a chance to reply?

Either way, my question is: Are these vulnerabilities inside the dependencies or the dev dependencies? If it's the latter only, there's nothing to worry about. If it's in the dependencies, most of the vulnerabilities should be fixed by maintenance. All the deps will be updated in our upcoming 4.1 release.
