### ISSUE TITLE
Pass custom args to saga through useInjectSaga From FC

### ISSUE THREAD

**Issue by ipenywis** [react-boilerplate/react-boilerplate#2731]
**Is your feature request related to a problem? Please describe.**
No way to get custom **args** through `useInjectSaga` to target Saga (Ex: for initialization, query API...)

**Describe the solution you'd like**
Allow `useInjectSaga` hook to receive a custom `...args` to be passed to the currently injected **Saga**.

**Describe alternatives you've considered**

**Additional context**
Simply passing spread ...args to injector:
```
const useInjectSaga = ({ key, saga, mode }, ...args) => {
  const context = React.useContext(ReactReduxContext);
  React.useEffect(() => {
    const injectors = getInjectors(context.store);
    injectors.injectSaga(key, { saga: saga, mode: mode }, args);

    return () => {
      injectors.ejectSaga(key);
    };
  }, []);
};
```
Then we can pass custom parameters from our component to the injected saga
`useInjectSaga({ key, saga: appSaga }, { isAuth: true });`
In the Target saga 
```
export default function* rootSaga(data) {
  console.log(data);
}
```

What do you think?

**Comment by julienben** [comment]
@ipenywis Thanks for this suggestion!

In the old HOC API for saga injection, the code passed props down to the sagas and I never understood why. Not sure that this is exactly the same usage but seems similar enough and very valid.

@BenLorantfy is currently working on extracting the injectors into a separate repo: http://github.com/react-boilerplate/injectors/

Once he's done (very soon), we'll be using these directly inside of react-boilerplate.

Do you mind posting the issue there since this is where all injector work will happen from now on? We can discuss and figure out the best way to proceed.

Thanks!!

**Comment by ipenywis** [comment]
Alright, I will post the issue in that repo.
Thanks!
