### ISSUE TITLE
Typescript in v5?

### ISSUE THREAD

**Issue by lsanders** [react-boilerplate/react-boilerplate#2768]
**Is your feature request related to a problem? Please describe.**

According to #2648 (which I can't comment on due to lock), it looks like there's some consensus with moving RBP to typescript! But, unless I'm missing it, I don't see any branch started. 

**Describe the solution you'd like**

I'm just wondering where I can follow the typescript progress and/or contribute. Very much looking forward to it.

**Describe alternatives you've considered**

@Can-Sahin's Fork

**Additional context**

**Comment by julienben** [comment]
Not aware of any Typescript branches either.

Personally I'm still ambiguous on Typescript, in part because it makes the learning curve even bigger.

I like the idea of a fork so that it keeps it optional. How up-to-date is the TS fork? Can we start by upgrading that?

**Comment by Can-Sahin** [comment]
TS fork is currently ahead of the master. I couldnt wait styled components v5 and merged the dev with my master to get the hooks and stuff. So its fully up to date. There are all the tests in TS. Only missing thing is `immer` which I still intentionally dont use coz of `readonly` alternatives in TS. But easy to implement. So its fully  TS fork for now. You can easily merge it. 

Personally TS makes learning curve bigger but overall development faster. Now I cannot write any js code. Without ts I feel like without any limbs. Its so faster to refactor the code build things that I dont look at weeks and can comeback and implement bug free features right away. TS is definitely a MUST for projects more complicated than 2-3 page web apps for me. It makes the whole process easier. We switched fully into TS in my company thats the reason I wanted to make a TS fork.

**Comment by aspirisen** [comment]
TS can be optional, it should run only if you have TypeScript files, otherwise it is still JS. And I agree with previous comment, you need TS if you create something bigger than landing page. It is one of the leading languages nowadays.

**Comment by Can-Sahin** [comment]
Yeah currently its optional, its extra transpiling layer. . Js code works as normal. I just dont write it anymore :)

**Comment by GrayStrider** [comment]
There are several problems with maintaining a fork though.
One of them is the fact that certain design decisions that make sense with the absense of strict typing, don't quite hold up when looked at through the prism of TypeScript. That leads to increased difficulty in merging, when the upstream updates ([one example](https://github.com/Can-Sahin/react-boilerplate-typescript/pull/35)) and holds the fork back.
Another thing to keep in mind: the purpose of the fork ([according to GitHub guidelines](https://hisaac.net/2016/11/12/why-commits-to-forks-on-github-dont-count-toward-contributions/)) is to be eventually **merged into the upstream**, otherwise there's no reason to keep a fork status on a project. While said status is in effect though, the work of the contributors does not show up on their profile page correctly (since it's expected to be merged to the upstream), which is a bit discouraging.
The solution would be to remove the fork status, but, returning to this specific discussion, for the [main TS fork](https://github.com/Can-Sahin/react-boilerplate-typescript/issues/53#issuecomment-546488292) of this project that would only make sense if there was a clear concensus on the future of upstream being JavaScript. 
I assume the decision would have to be collectively made by the core project members, so I'm looking forward for the contunuation of this discussion.

**Comment by julienben** [comment]
That makes a lot of sense. IMO we have two options going forward:

1. Merge the fork into react-boilerplate and have it become the official project. With TypeScript optional.
2. Make it an official but separate project in the react-boilerplate organization.

Thoughts?

**Comment by GrayStrider** [comment]
> 1. Merge the fork into react-boilerplate and have it become the official project. With TypeScript optional.

Merge as in create separate branch for TypeScript? Or actually merge into master, with `allowJs: true` in `tsconfig.json`?

**Comment by julienben** [comment]
Well I guess first as a branch to "finalize" it locally (docs, maybe some config?). Then eventually into `dev` and then into `master` when it would be released, perhaps as v5.

**Comment by GrayStrider** [comment]
On a sidenote, there are several _very_ outdated versions of packages used in project's utility scripts, versions before types were even added there, so substantial rework might be required. In the fork, we are now pretty much forced to use `any` for these, to avoid large conflicts with the upstream, which is suboptimal.

**Comment by GrayStrider** [comment]
> first as a branch to "finalize" it

Works for me. @Can-Sahin , I suppose we should bring the fork to a "mergeable" state, create separate branch (in case some changes will be added before the transfer finishes) and then give the go-ahead?
Some other technicalities, perhaps?

**Comment by GrayStrider** [comment]
> 2. Make it an official but separate project in the react-boilerplate organization.

I see several problems with this approach. Given it won't be a fork anymore (even though changes from the upstream would still be merged), there will be essentially 2 identical codebases, one with types, the other without. That would - second problem - lead to situations when a change, proposed to TS version, would be better first applied to upstream (something not TS-specific, for example), so the contributor would have to be redirected there, etc etc.
So, indeed, the former option would be preferrable.

**Comment by julienben** [comment]
I agree. The first option is preferable.

There's only two reasons I'm personally on the fence:
- I still hear so much ambiguity on TS and feel like the jury is still out on how much it brings to a project vs the cost of using it.
- It makes the barrier to entry much higher. (And also, on a more personal note, I've never used it so it prohibits me from contributing until I've taken the time to learn it.)

**Comment by Can-Sahin** [comment]
I think javascript-typescript optional is a pretty good idea. 

(assuming that merging is gonna happen) @GrayStrider yes definitely lets arrive to a mergeable state in ts fork. (But as I said can you take the non-ts changes as a side note to implement later after we merge into a dev branch or something. Because I still need to pull in from the upstream. Don't wanna drive apart so much. Would be soo easier if we merge first into a dev branch or something then carry on there.

@julienben I don't think getting used to typescript gonna be hard. I admit it was hard for me in the beginning but already solved all the issues pretty much and packages are getting more suitable for typescript everywhere. Been maintaining it actively over a year now. Potentially people could still commit with js-like code and we could fix the typings etc (if its really necessary). I can do comparison and entrance guide to typescript version (like whats is added and how is it used) so would be even easier for core developers to track whats going on, to get onboard.

**Comment by GrayStrider** [comment]
> people could still commit with js-like code and we could fix the typings

Yes, I second this. It doesn't stop you or anyone from contributing, but perhaps passing the PR review might be a bit trickier, which isn't necessarily a bad thing:)
As another example of TS goodness: there are a few tests present that are simply redundant with TS, since those specific testing scenarious would fail at compilation anyway (incompatible types). 

PS.
> people could still commit with js-like code

Although I would very much like to see `noImplicitAny: true` and no explicit any at some point in the future:)
TypeScript **eliminates the ambiguity**. I was adding proper typings to project's tests recently, and figuring out what does what, why that piece is used here, what is this, how does that work etc etc. takes quite a while; I had to manually "search for usage" for each component to get a grasp of how is it intened to be used. With TS that is no longer the case: every type is explicitly/implicitly defined, and the intent of the programmer is crystal clear.

**Comment by Can-Sahin** [comment]
@GrayStrider @lsanders @julienben 

For this issue, I think for now the best thing to do is move typescript fork into this organization and remove the fork status (sending request to github). What do you think ?

I dont think merging typescript into this and maintaining a hybrid system isn't doable in near future. There are quite a lot of typescript only features and these will be conflicting the original source code and will eventually lead us to make separate folders with the `app` folder. On top of it, seeing `ts` and `js` mixed could potentially make newcomers confused and walk away (especially if not familiar with `ts`). I think starting with the boilerplate is already complicated for beginners. 

Any feedback ?

**Comment by Can-Sahin** [comment]
I moved my fork to this organization and removed fork dependency. So I will be maintaining it here and any help would be so nice if you are interested. Closing this issue. We can discuss on another issue when merging two becomes possible ;)

**Comment by sureshtidbit** [comment]
so can you tell me approx when you will try to merge and solve the issue so we can plan our project accordingly? @Can-Sahin

**Comment by Can-Sahin** [comment]
@sureshtidbit well I see 50% chance in not merging. Even if it will, it's gonna take a long time. You can just start from `ts` version. Its under this github organization now you can find easily. I'm waiting for `5.0` and will update quickly as soon as it lands. However, it is working now too, check it out. It's in a minor version `4.1` mainly because I started a new project and I couldn't wait `5.0` and did a minor update with hooks and dependencies.
