### ISSUE TITLE
Use class react component in index.js file?

### ISSUE THREAD

**Issue by lolgolflol** [react-boilerplate/react-boilerplate#2785]
## Description
I use a generate command and input this below. 
? What should it be called? Transaction
? Do you want to wrap your component in React.memo? Yes
? Do you want headers? Yes
? Do you want an actions/constants/selectors/reducer tuple for this container? Yes
? Do you want sagas for asynchronous flows? (e.g. fetching data) Yes
? Do you want i18n messages (i.e. will this component use text)? Yes
? Do you want to load resources asynchronously? Yes

And I got a index.js (screenshot below) and a Loadable.js file.  My question is : I would like this component has a state by itself. when I change to Class, It's errors.
and Could you recommend an open-source project power by react-boilerplate for as an example? I would like to research technic most people use.
```
export default class Transaction extents React.component {
  state = {
  }
  ........
}
```

## Steps to reproduce

**Expected behavior**
Change function in index.js file to extends component react. I would like to this file has a state by itself. 

**Screenshots**
<img width="879" alt="Screen Shot 2019-10-21 at 4 47 50 PM" src="https://user-images.githubusercontent.com/1137330/67196561-43349e80-f425-11e9-9067-30edcb10e1a8.png">

## Versions

- React-Boilerplate:
- Node/NPM:
- Browser:

**Comment by julienben** [comment]
Hi @lolgolflol, Our generators use the new Hooks API from react. It uses functions instead of classes but you can still do pretty much everything you would inside of a class component, including using local state. You can read about the Hooks API [here](https://reactjs.org/docs/hooks-intro.html).

If you'd prefer to use classes, you can use the old generators from version 3.7 of the boilerplate.
