### ISSUE TITLE
Outdated Package

### ISSUE THREAD

**Issue by mernstackman** [react-boilerplate/react-boilerplate#2799]
## Description
Many dependency packages are outdated. Is it recommended to update them or should I stick to the version used in boilerplate to avoid code changes?

I see security warning for lodash, so I issued this question.

## Steps to reproduce
- Install react-boilerplate
- Open its folder in terminal
- run: npm outdated
it will list the outdated packages.

**Expected behavior**
The "npm outdated" supposed to not return any package name in the outdated list and no security issue report is shown during setup.

**Screenshots**
Currently here is the outdated packages:
![outdated_packages](https://user-images.githubusercontent.com/4498399/68094762-3a88a180-fed6-11e9-8337-11a6daa98a60.jpg)

## Versions

- React-Boilerplate: 4.0.0
- Node/NPM: 10.16.2/6.9.0
- Browser: Firefox 70.0b8 (64-bit)

**Comment by julienben** [comment]
Hey @mernstackman,

V4.0.0 came out in April and indeed many dependencies have been upgraded since then.

My personal recommendation is to maintain your dependencies and keep them up to date as much as possible while of course being careful of breaking changes.

Because react-boilerplate is a boilerplate and not a dependency (like a pre-ejected create-react-app), you have to do that manually in your own project.

The [V4.1 PR](https://github.com/react-boilerplate/react-boilerplate/pull/2686) shows all the maintenance work/dependency upgrades which have been done since V4.0 and should help you do that on your side.

Best of luck!
