### ISSUE TITLE
Post call failing with 401

### ISSUE THREAD

**Issue by IlliyazSyed** [react-boilerplate/react-boilerplate#2840]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
Getting 401 for post calls from saga

## Steps to reproduce
In my saga I am using below generator to make a post call and passing the right token, url and other details. Even same call is getting successful with postman.

export function* getCPSDetails() {
   
  const requestURL = '';
  const proposalID = yield select(makeSelectProposalID());
  const payload = {
    method: 'POST',
    credentials: 'include',
    mode: 'no-cors',
    headers: {
      'AuthenticationToken': '',
      'Content-Type': 'application/json',
      'Accept': 'application/json'
            },
    body: JSON.stringify({
                            "UserName": "",
                            "LocaleCode": "",
                            "AgreementNumber": "",
                            "ProposalID": ""
                            "ValidationType": ""
                         }),
     
    
  };

(Add link to a demo on https://jsfiddle.net or similar if possible)

**Expected behavior**
should get a response

**Screenshots**
Response Headers
Access-Control-Allow-Origin: http://localhost:3000
Content-Length: 0
Date: Fri, 13 Dec 2019 11:39:49 GMT
Request-Context: appId=cid-v1:e8b53ae8-fd1d-4d01-a0c2-4662c2ad3d58
Server: Kestrel
WWW-Authenticate: Bearer
X-Powered-By: ASP.NET

Request Headers
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 136
Content-Type: text/plain;charset=UTF-8
Host: xxxxxxxserviceuat.azurewebsites.net
Origin: http://localhost:3000
Referer: http://localhost:3000/
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

## Versions

- React-Boilerplate:v4.0.0
- Node/NPM:v8.15.1 
- Browser:Chrome

**Comment by tonychew1986** [comment]
Getting similar issues here

**Comment by Can-Sahin** [comment]
This doesn't look like a boilerplate issue. It can be literally any reason depending on your both client and server configuration. 

My personal guess, the problem is with the `OPTIONS` request (PREFLIGHT). You are sending tokens in Auth header and Postman does NOT send preflight requests unlike your browser. That might cause `401` if `OPTIONS` request does not include token or since its cross origin request server might reject auth simply. Check your configurations. If the problem is really the actual request and not related to CORS or PREFLIGHT then we can open the issue again if you can provide a sample repository reproducing the error.
