### ISSUE TITLE
Issue: Using Local Font without styled componenets

### ISSUE THREAD

**Issue by Abdulhakimsg** [react-boilerplate/react-boilerplate#2844]
**Description**
I am trying to install noto-sans font locally without the use of styled components.

**Steps to reproduce**

I have added `@font-face` to my fonts.css and imported the fonts in app.js.However, i am unable to get any of my NotoSans.tff fonts to work.

`app/styles/font.css`
```
@font-face {
  font-family: 'Noto Sans', sans-serif;
  font-style: normal;
  font-weight: 400;
  src: url('../fonts/NotoSans-Regular.ttf') format('truetype');
}
```

`app/styles/index.css`
```
@import './fonts.css';
```

`app/app.js`
```
import './styles/index.css';
```

All help is appreciated. Thank you

**Expected behavior** 
App to load appropriate font

**Versions**
React-Boilerplate:v4
Node/NPM:>=8.10.0
Browser:Chrome 78

**Comment by Can-Sahin** [comment]
I had no issue using a local font. You can have a look at the [working example](https://github.com/International-Slackline-Association/Slackline-App/blob/master/app/styles/font-face.css)

I don't understand the styled-components part. It isn't really dependent on that. Importing it somewhere makes it work with or without the styled-components. 

What does this mean `@import './fonts.css';` ? Where is the `@` symbol pointing at? Shouldn't it be without `@` or are you sure you are importing it with the correct paths?

**Comment by julienben** [comment]
`@import` is a valid CSS rule but I'm not sure it will work with Webpack in this case. (Since it's browser-resolved but `font.css` might not exist in the Webpack output.) Try to put the contents of `font.css` directly inside your `styles/index.css` file and debug from there.

Closing this for now. Please reopen if you identify a specific react-boilerplate bug (i.e. something broken in the project code vs something that needs to be fixed in your personal font setup).
